Bn fabb80
BetaMasaheft/Manuscripts pull request #1111
Opened 2021-05-26 20:47 UTC by MarcinKrawczuk

2021-06-01 08:21 UTC, DenisNosnitsin1970 requested changes
Please add to the description the infor on ruling:  <ab type="ruling"> The upper line is written below the ruling.</ab><ab type="ruling"> The bottom line is written above the ruling.</ab>
I personally inclined to think that Conti Rossini's dating is too broad, he himself might have included only 16th century because of the form of "lo" which he found modern, but this form do occurs in the 15th century and before.

2021-06-17 08:06 UTC, DenisNosnitsin1970 requested changes

2021-06-17 21:40 UTC, MarcinKrawczuk commented on ParisBNF/abb/BNFabb80.xml
> +            <citedRange unit="page">93-94</citedRange>
I checked the pdf of d'Abbadie's catalogue and it seems correct.

2021-06-18 12:35 UTC, DenisNosnitsin1970 approved these changes

2021-06-18 17:38 UTC, MarcinKrawczuk commented on ParisBNF/abb/BNFabb80.xml
> +     <ab type="ruling"> The upper line is written below the ruling.</ab>
I hope I chose the correct ruling pattern, I don't have much experience with that, I'm afraid.

2021-06-18 17:39 UTC, MarcinKrawczuk commented on ParisBNF/abb/BNFabb80.xml
> +
Done.

2021-06-18 17:42 UTC, MarcinKrawczuk commented on ParisBNF/abb/BNFabb80.xml
> +            <citedRange unit="number">133</citedRange>
I don't have this reprint, only the original from Journal Asiatique in parts.

2021-06-18 17:52 UTC, MarcinKrawczuk commented on ParisBNF/abb/BNFabb80.xml
> +
Added <history>

2021-06-21 09:02 UTC, DenisNosnitsin1970 approved these changes

2021-06-21 09:02 UTC, merged