rdw005
BetaMasaheft/Manuscripts pull request #1182
Opened 2021-07-06 14:19 UTC by thea-m

I would be grateful if you could have a look at the encoding of this scroll, in which I have tried to incorporate the outcomes of the many scroll issues of the past.

I have two specific questions:
- the locus in ms1 is commented out, because it leads to an error message as it doesn't start with a digit. Does the schema need to be updated or the guidelines?
- I have (out of habit) numbered the lines continuously through the entire scroll, not section by section or text by text. What would be preferable here?

Thank you!

2021-07-08 07:47 UTC, DenisNosnitsin1970 requested changes

2021-07-08 07:47 UTC, DenisNosnitsin1970 commented on Hamburg/HLC/RDW005.xml
> +                              <note>Number of characters per line: </note>
No numbers, here and below?

2021-07-08 07:47 UTC, DenisNosnitsin1970 commented on Hamburg/HLC/RDW005.xml
> +                              <note>Number of characters per line: </note>
Where text area 1 end? Where text area 2 starts?

2021-07-08 07:47 UTC, DenisNosnitsin1970 commented on Hamburg/HLC/RDW005.xml
> +                        <decoNote xml:id="b1" type="SlipCase">The scroll is kept in a case probably made of reptile skin.</decoNote>
Perhaps a more specific term can be used to refer to the traditional container (?) used for keeping Ethiopic scrolls. Is it European- or Ethiopian-made?

2021-07-08 11:03 UTC, thea-m commented
@DenisNosnitsin1970 , thank you! But you accidentally looked at an older version of the file, could you check the latest one (this has the characteres per line and text area correspondences):
 https://github.com/BetaMasaheft/Manuscripts/pull/1182/files
I think that the container is Ethiopian-made. Do you know a more specific term?
![image](https://user-images.githubusercontent.com/19650382/124911250-d1332d00-dfec-11eb-84fd-3344e6242342.png)
![image](https://user-images.githubusercontent.com/19650382/124911280-dc865880-dfec-11eb-874b-1dbf174ae8f6.png)

2021-07-08 11:52 UTC, DenisNosnitsin1970 requested changes
Strelcyn uses "cylindrical leather case", or "(beautiful) cylindrical silver case", or "cylindrica case made of .... (covered with)". I wonder what is a traditional Amharic or TGN term for this (Amhars would possibly say መያዣ, but it is "container", there may be a specific word for this, we have to ask around). 
It is indeed the first case that I see a part of a manuscript made of such a skin looking like a reptile skin.  
l. 52: ቁመኛ or ቂመኛ?

2021-07-08 11:52 UTC, DenisNosnitsin1970 commented on Hamburg/HLC/RDW005.xml
> +                     <lb n="71"/>ብርያይስ፡ ወ
probably it is ጥብርያዶስ or ደስ

2021-07-12 12:10 UTC, thea-m commented
Thank you, I checked the manuscript and carried out a few corrections in the text.
@DariaElagina and @PietroLiuzzo , it would be great if you could also have a look :)

2021-07-12 14:32 UTC, PietroLiuzzo commented
from the guidelines 
- https://betamasaheft.eu/Guidelines/?q=referencing&id=referencing-the-manuscript 
- https://betamasaheft.eu/Guidelines/?q=scroll&id=scrolls

I think you can choose from several options for referencing
- using `<locus>`, in which case, you do need to state a `<pb n='1r'>`
````xml
 <msItem xml:id="ms_i1">
                     <locus from="1r1" to="1r41"/>
                     <title type="complete" ref="LIT6473PPAynaTela"/>
                    <textLang mainLang="gez"/>
                     <note>See the transcription of the incipit and explicit in <ref target="#text1"/>.</note>
                  </msItem>  
````

- using `<ref type="mss" corresp="RDW005.recto.sec2.1"/>` which however is not allowed in `<msItem>`.
````xml
 <msItem xml:id="ms_i1">
                     <title type="complete" ref="LIT6473PPAynaTela"/>
                    <textLang mainLang="gez"/> 
                     <note>
<ref type="mss" corresp="RDW005.recto.sec2.1-41"/>
See the transcription of the incipit and explicit in <ref target="#text1"/>.
</note>
                  </msItem>  
````

2021-07-12 14:33 UTC, PietroLiuzzo commented
The numbering of lines is IMHO not really an issue, if it has been done one way, it can stay that way without affecting the encoding or its reuse

2021-07-13 12:11 UTC, thea-m commented
Thank you, Pietro!

2021-07-14 09:39 UTC, DariaElagina approved these changes

2021-07-14 12:11 UTC, merged