Add 19892
BetaMasaheft/Manuscripts pull request #1272
Opened 2021-09-28 09:15 UTC by DariaElagina

2021-09-28 11:10 UTC, Hasnake approved these changes

2021-09-28 11:22 UTC, Hasnake approved these changes

2021-09-28 20:05 UTC, DenisNosnitsin1970 requested changes

2021-09-28 20:05 UTC, DenisNosnitsin1970 commented on LondonBritishLibrary/add/BLadd19892.xml
> +                <title>Malkǝʾa Māryām, qǝddase Māryām, maṣḥafa saʿātāt, saʿātāt</title>
Please correct: Qǝddase, Maṣḥafa, Saʿātāt

2021-09-29 13:28 UTC, Getinet309 commented on LondonBritishLibrary/add/BLadd19892.xml
> +                <title>Malkǝʾa Māryām, qǝddase Māryām, maṣḥafa saʿātāt, saʿātāt</title>
<colophon xml:id="coloph1" xml:lang="gez">
  <locus target="#201r"></locus>
  ዛቲ፡ ጸሎት፡ ዘ<persName ref="PRS13556HabtaM" role="scribe">አባ፡ ሐብተ፡ ማርያም፡</persName>
  <sic>ዘደብረ፡</sic> ዘጸሐፍክዋ፡ በሮምያ፡
  ውስተ፡ <placeName ref="INS0302SanStefano">ደብረ፡ ቅዱስ፡ እስጢፋኖስ፡ ዘማኅበረ፡ ኢትዮጵያውያን፡</placeName>
  <sic>በመዋዕለ፡</sic> <persName ref="PRS9682UrbanVI">ሊቀ፡ ጳጳሳት፡ <sic>ኡባኖስ።</sic></persName>
  ሳምናይ፡ ዘመንበረ፡ ቅዱስ፡ ጴጥሮስ።
  <date>ወዓመተ፡ ምሕረትሂ፡ ፲፻፮፻ወ፵፡ እምልደተ፡ ክርስቶስ፡ እግዚእነ።</date>
  <gap reason="ellipsis"></gap>

2021-09-29 13:30 UTC, Getinet309 requested changes
I hope there is missed text next to  "በደብረ"

2021-09-29 13:47 UTC, DariaElagina commented
Dear Getinet, 
thank you for your correction. Actually, the text of the manuscript is imperfect and reads በዋዕለ፡ and has nothing after በደብረ. That is also why those words are surrounded by a sic element, which indicates that the text follows the manuscript, although the text appears to be incorrect.

2021-09-29 14:14 UTC, merged