Update BLorient566.xml
BetaMasaheft/Manuscripts pull request #1329
Opened 2021-11-29 10:57 UTC by DariaElagina

2021-11-29 13:24 UTC, thea-m requested changes
Thank you!

2021-11-29 13:24 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient566.xml
> +                              <hi rend="rubric">ጸሎተ፡ ግትሐት፡ ሌዊ፡ ሌዊ፡ ሌዊ፡ ሌዊ፡ ሌዊ፡ ሌዊ፡</hi>
ግትሐት in the ms?

2021-11-29 13:24 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient566.xml
> +                              <desc type="findingAid">Finding aids, colored pieces of threads in blue
I think that these are leaf string markers and should be encoded in the description of the binding

2021-11-29 13:24 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient566.xml
> +                          with the directions for their use.</note>
accompanied by directions, I think

2021-11-29 15:11 UTC, DenisNosnitsin1970 requested changes

2021-11-29 15:11 UTC, DenisNosnitsin1970 commented on LondonBritishLibrary/orient/BLorient566.xml
> +                              <hi rend="rubric">በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩አ</hi>ምላክ፡ ጸሎት፡ በእንተ፡ መፍትሔ፡ ሥራይ፡
I would include መፍትሔ፡ ሥራይ into the title

2021-12-03 09:21 UTC, thea-m approved these changes

2021-12-03 09:21 UTC, merged