Emml1194
BetaMasaheft/Manuscripts pull request #1341
Opened 2021-12-03 14:09 UTC by MarcinKrawczuk

I am sending the catalog description, I have a pdf copy of the ms. if needed.
[EMML 1194 opis.pdf](https://github.com/BetaMasaheft/Manuscripts/files/7650151/EMML.1194.opis.pdf)

2021-12-06 13:35 UTC, thea-m requested changes

2021-12-06 13:35 UTC, thea-m commented on EMML/1001-2000/EMML1194.xml
> +<q xml:lang="gez">ቃለመ፡ ወርቅ፡ ለውጤ፡ ዘአሸማ፡ ቂርቆስ፡ ወዘጓ፡ ጊ<supplied reason="omitted">ዮርጊስ</supplied>፡</q>
ቃለመ or ቀለመ?

2021-12-06 13:35 UTC, thea-m commented on EMML/1001-2000/EMML1194.xml
> +<desc type="ScribalSignature">The name of the scribe is <persName role="scribe" ref="PRS13645Qalama">Qalama Warq Lawtē</persName>. According to the catalog, pages 1-95
Lawwəṭṭe, I think?

2021-12-06 13:35 UTC, thea-m commented on EMML/1001-2000/EMML1194.xml
> +have been copied by <persName role="scribe" ref="PRS13646Makwannen">Makʷannen Gabra Śellāsē</persName>.</desc>
Śəllāse

2021-12-06 19:56 UTC, MarcinKrawczuk commented on EMML/1001-2000/EMML1194.xml
> +<q xml:lang="gez">ቃለመ፡ ወርቅ፡ ለውጤ፡ ዘአሸማ፡ ቂርቆስ፡ ወዘጓ፡ ጊ<supplied reason="omitted">ዮርጊስ</supplied>፡</q>
ቀ

2021-12-06 19:57 UTC, MarcinKrawczuk commented on EMML/1001-2000/EMML1194.xml
> +have been copied by <persName role="scribe" ref="PRS13646Makwannen">Makʷannen Gabra Śellāsē</persName>.</desc>
Of course :/

2021-12-08 10:26 UTC, thea-m approved these changes
Thank you!

2021-12-08 10:26 UTC, merged