Update BDLaethc14.xml
BetaMasaheft/Manuscripts pull request #1345
Opened 2021-12-06 14:31 UTC by gnizla

a) it's been a while since I did a pull, so want to make sure I am doing everything properly before uploading other stuff.
b) while working on this I was truck that it would be nice to include references in deco summary, but it's not allowed to use <bibl> is there a way to do this on guidelines?

2021-12-06 16:02 UTC, thea-m requested changes
Thank you! Everything is fine, I just have one small question. I included the reference (please check that it's the correct one), I didn't get an error message.

2021-12-06 16:03 UTC, gnizla commented on OxfordBodleian/Juel-Jensen/BDLaethc14.xml
> +                             <desc> A <term>standing</term>
I can easily do away with Term thanks

2021-12-06 16:08 UTC, gnizla commented
> Thank you! Everything is fine, I just have one small question. I included the reference (please check that it's the correct one), I didn't get an error message.

I don't know, maybe I got an error because of the way I coded it, will amend and then push other stuff, thanks,

2021-12-08 16:36 UTC, thea-m approved these changes
Thank you, Jacopo! Everything seems wonderful to me. I corrected some minor typos and the encoding of term with ana instead of key, which I believe was due to automatic content completion, not intention (let me know if I'm mistaken).

2021-12-08 17:02 UTC, gnizla commented
Thank you so much for your prompt reply and work @thea-m, you are a star!

2021-12-08 17:10 UTC, merged