Jj gnisci
BetaMasaheft/Manuscripts pull request #1368
Opened 2021-12-29 01:24 UTC by gnizla

- I have changed the dating suggested by SH for b4 from 1600-1800 to 1750-1850 on the basis of miniatures
- There are a lot of miniatures in b. 4! The identification of d. 36, d. 37, and d. 38 is a bit tentative in case you have any insight.
- I am a bit uncertain about how to visualize layout, this is something that can be resolved further down the line though.

2021-12-29 17:10 UTC, MassimoVilla requested changes
Thank you Jacopo! I have just a couple of trivial remarks, perhaps typos.

2021-12-29 17:12 UTC, gnizla commented on OxfordBodleian/Juel-Jensen/BDLaethb4.xml
> +      Above, two tortures hit <persName ref="PRS13193Giyorgis">St George</persName>
Yes, well spotted, will change.

2021-12-29 17:12 UTC, gnizla commented on OxfordBodleian/Juel-Jensen/BDLaethb4.xml
> +       in a pool at the foot of a hill surmounted by a Gondarene castle; to the right, an executioner has cut off their heads (full-page).
Both terms are attested in the literature :)

2022-01-07 18:03 UTC, thea-m requested changes
Thank you! One extremely minor remark. 
I corrected some typos directly in the files (also old ones in other parts of the description). 
I do join Massimo in his Gondarene/Gondarine question: Both are used in our records, to me it seems better to agree on one (I have no opinion which).

2022-01-09 17:41 UTC, gnizla reviewed
Thanks for comments!

2022-01-09 17:46 UTC, merged

2022-01-10 07:43 UTC, gnizla commented
I do join Massimo in his Gondarene/Gondarine question: Both are used in our records, to me it seems better to agree on one (I have no opinion which).

Gondarine is more common than Gondarene so I guess it would make more sense to go for that if we want standardization. @sologebre any opinion?