BDLaethf26
BetaMasaheft/Manuscripts pull request #1430
Opened 2022-02-11 10:48 UTC by thea-m

And the next one - obviously, please take your time.
As always, I stay within a wide range for the palaeographic dating - if anyone sees evidence for restricting this range, I'll be happy.
@sologebre can you make some meaning out of the Amharic notes at the end?
Thanks a lot!

2022-02-11 11:03 UTC, sologebre reviewed
-The Amharic text only reads that it was written in 1930, which is exactly the year. Perhaps you could have found other references in the MSS. 
_spacing: ክርስቲያን፡  ቅድስት፡

2022-02-11 12:11 UTC, ElianaDalSasso approved these changes
Thank you Thea! Great work, I committed just two typos and added two comments. One is on the irregular ruling pattern. It doesn't seem to be made on purpose so I would not change to B or ! but perhaps it is interesting to add a note.

2022-02-11 14:36 UTC, MassimoVilla requested changes
Very good, thank you Thea! Just some minor observations!

2022-02-12 16:20 UTC, gnizla approved these changes

2022-02-12 16:21 UTC, gnizla approved these changes

2022-02-14 10:50 UTC, thea-m commented on OxfordBodleian/Juel-Jensen/BDLaethf26.xml
> +                                    <q xml:lang="en">Ethiopic MSS 2&amp;3
Yes, this is how & has to be escaped in XML (the other characters to be escaped are < and >), it will be printed as &.

2022-02-14 10:53 UTC, thea-m commented on OxfordBodleian/Juel-Jensen/BDLaethf26.xml
> +                                    <seg type="rubrication">Groups of lines at the beginning; holy names; the word <foreign xml:lang="gez">ሰላም፡</foreign>;
ah, my mistake - we had agreed on holy names previously. Good that you spottet it!

2022-02-14 10:54 UTC, thea-m commented
Thanks everyone! I believe I incorporated all your corrections.

2022-08-01 18:53 UTC, merged