IDs changed
BetaMasaheft/Manuscripts pull request #1463
Opened 2022-02-23 10:45 UTC by vitagrazia81

I have changed the Ids of  the Munich manuscripts. Could you please check them :-)?

2022-02-23 10:50 UTC, thea-m requested changes
Thank you! Is it possible that for Munich 2, 5, and 6 you forgot to change the xml:id inside the file? Could you check that again?

2022-02-23 11:35 UTC, vitagrazia81 commented
Dorothea, thank you. Could you check again now?

2022-02-23 13:29 UTC, thea-m approved these changes

2022-02-23 13:29 UTC, merged

2022-02-24 08:16 UTC, vitagrazia81 commented
Thank you Dorothea. 
Just a thing: I have seen them online (e.g. https://betamasaheft.eu/manuscripts/MfVK86307647/main) but you don't see the shelfmark anymore. This is for all manuscripts. They are not displayed.  On the xml files there are, I have encoded them (under  <idno>.,,,). Do you think is a bug?