Max 12
BetaMasaheft/Manuscripts pull request #1477
Opened 2022-03-01 14:15 UTC by MassimoVilla

Here comes a new manuscript. MS BDLaethg31 is a small codex containing two apocryphal texts and one liturgical text. Two of them were previosuly unrecorded in BM.

2022-03-02 00:29 UTC, gnizla commented on OxfordBodleian/Juel-Jensen/BDLaethg31.xml
> +                <title xml:lang="en" corresp="#title1"> Prayer of Our Lady Mary on Mount Golgotha, </title>
Not doing proofreading, as we discussed last meeting, but is the comma intentional?

2022-03-02 00:29 UTC, gnizla commented
Thank you "King" Max (as Solomon calls you!)

2022-03-02 09:58 UTC, ElianaDalSasso approved these changes
Thank you Massimo! Just a minor comment on the bindingDesc of g. 31. However, I need to look at it in detail.

2022-03-02 11:56 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethg31.xml
> +                                <decoNote xml:id="b1">Two <material key="wood">wooden</material> boards covered with dark red <material key="leather"/>.
I am unable to judge from the pictures, but the pasteboard option seems now preferable to me too.

2022-03-07 12:00 UTC, thea-m requested changes
Thanks a lot! A few minor remarks, mostly encoding-related.

2022-03-07 16:53 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethg31.xml
> +                            <incipit xml:lang="gez" type="supplication">
my mistake: I reduplicated the `<incipit xml:lang="gez" type="supplication">` element without changing/removing "supplication"

2022-03-07 16:59 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethg31.xml
> +                                <decoNote xml:id="b1">Two <material key="wood">wooden</material> boards covered with dark red <material key="leather"/>.
P.S. I am seeing that "pasteboard" is not allowed as a value in `<material key="pasteboard"/>`. Should it be added to the allowed values in this position?

2022-03-07 17:06 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethg31.xml
> +                                    A poorly understandable note has been written in an untrained hand. The text reads as follows: <q xml:lang="gez">ወልደ፡ ጊዮርጊስ፡ ምንሱቅ<supplied reason="omitted">፡</supp
Good! Please check if now the description of a1 is formulated properly.

2022-03-07 17:31 UTC, ElianaDalSasso commented on OxfordBodleian/Juel-Jensen/BDLaethg31.xml
> +                                <decoNote xml:id="b1">Two <material key="wood">wooden</material> boards covered with dark red <material key="leather"/>.
Yeah, you're right it needs to be added. I used to create keywords but I think that here the process is different and might involve changes to the ODD. Am I wrong? Does anyoneone know how to do it?

2022-03-08 15:13 UTC, thea-m commented
Thank you! It's fine by me, let's keep it open until the new value exists, so that we don't get in the habit of using non-existent values :) Maybe in the meanwhile Solomon might have some input on the note.

2022-03-09 11:16 UTC, thea-m commented
I was about to open the issue and then noticed that we do have the value "cardboard" - is that the same as pasteboard (or is it used in the same way in the existing records)?

2022-03-10 16:03 UTC, ElianaDalSasso commented
Sorry for the delay! 
- @thea-m I explored a little the Ligatus terminology. It seems that pasteboard is now considered an improper term to refer to boards made from pasted laminations of paper (http://w3id.org/lob/concept/1492). Then there is Card, a term " without a specific definition" used "to describe a relatively stiff thick paper or a thin paper board" http://w3id.org/lob/concept/4614. They do not define cardboard....but the Oxford English Dictionary defines it as: "Thick, stiff paper or pasteboard, used for making boxes, etc. Also (now rare): a piece of such material". From what I know, the boards made of paper can be formed either by sheets of paper pasted together (pasteboard) or by a thick pulp of paper fibres (pulp board)...and here arises the confusion.
In the end, the terms cardboard, pasteboard, pulp board, pasted-laminated boards seem very (too much) specific to me. I am wondering if the term 'paper' could be added as a value instead. This would permit to say: 
`<decoNote xml:id="b1">Two boards made from pasted laminations of <material key="paper">paper</material> ` or
`<decoNote xml:id="b1">Two boards made of <material key="paper">paper</material> pulp` perhaps also
`<decoNote xml:id="b1">Two boards made of stiff thick <material key="paper">paper</material>` or 
`<decoNote xml:id="b1">Two  <material key="paper">paper</material> boards` would work.
- However, I was thinking that I am just supposing that the boards are not made of wood based on the style of the binding but having not seen them in person, I could also be wrong. 
- @MassimoVilla I can do it! I have to go through all bindingDesc anyway.

2022-03-14 15:24 UTC, thea-m commented
Thank you! I opened an issue about the general use of "cardboard". Regardless of that, the term "paper" already exists, so that might be a good solution here?

2022-03-25 11:18 UTC, ElianaDalSasso commented
No bothering at all! The discussion is still opened in the issue #2009 open by @thea-m. We could use tentatively use the value "paper" until the issue is solved!

2022-03-28 08:27 UTC, merged

2022-03-28 08:27 UTC, thea-m commented
Thanks @MassimoVilla and everybody!