BLorient590
BetaMasaheft/Manuscripts pull request #1692
Opened 2022-05-12 18:00 UTC by thea-m

@MarcinKrawczuk

2022-05-12 18:02 UTC, thea-m commented
(Can you just review BLorient590, I will look at the conflict in the other file later)

2022-05-12 18:57 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient765.xml
> -
as always, I am in favour of the empty element, as it lets the overall summary be generated and printed

2022-05-12 19:42 UTC, DenisNosnitsin1970 requested changes

2022-05-12 19:42 UTC, DenisNosnitsin1970 commented on LondonBritishLibrary/orient/BLorient590.xml
> +                <title>Ṭabiba Ṭabibān, collection of salām-hymns</title>
I would write: Collection of ...

2022-05-13 09:21 UTC, thea-m commented
Solved conflict

2022-05-14 01:53 UTC, eu-genia approved these changes

2022-06-08 11:40 UTC, merged