Abb 7 78 90 168 199 203 BL
BetaMasaheft/Manuscripts pull request #1778
Opened 2022-07-19 14:28 UTC by DenisNosnitsin1970

New records, corrections and updates to older records.

2022-07-19 15:24 UTC, thea-m requested changes

2022-07-19 15:24 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient691.xml
> +                    but it is located on the last page <ref target="#241vb"/> and should
locus, not ref

2022-07-19 15:24 UTC, thea-m commented on ParisBNF/abb/BNFabb168.xml
> +                                <note>The first leaf <ref target="#i"/> is neither ruled nor pricked.</note>
locus

2022-07-19 15:24 UTC, thea-m commented on ParisBNF/abb/BNFabb199.xml
> +                           bequethed to <persName ref="PRS1071dAbbadi"/>.
bequeathed

2022-07-19 15:24 UTC, thea-m commented on ParisBNF/abb/BNFabb203.xml
> +                          <explicit xml:lang="">
language value missing

2022-07-19 15:24 UTC, thea-m commented on ParisBNF/abb/BNFabb203.xml
> +                bequethed to <persName ref="PRS1071dAbbadi" role="owner"/>.
bequeathed

2022-07-19 15:24 UTC, thea-m commented on ParisBNF/abb/BNFabb90.xml
> +                                  assigned the number <locus target="#207">115</locus>.</foliation>
207 or 115?

2022-07-20 09:55 UTC, DenisNosnitsin1970 commented on LondonBritishLibrary/orient/BLorient691.xml
> +                    but it is located on the last page <ref target="#241vb"/> and should
ok

2022-07-20 09:58 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb199.xml
> +                           bequethed to <persName ref="PRS1071dAbbadi"/>.
ok

2022-07-20 09:59 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb203.xml
> +                          <explicit xml:lang="">
ok

2022-07-20 10:09 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb90.xml
> +                                  assigned the number <locus target="#207">115</locus>.</foliation>
115

2022-07-20 12:06 UTC, thea-m approved these changes

2022-07-20 12:06 UTC, merged