Abb217 juste
BetaMasaheft/Manuscripts pull request #1810
Opened 2022-08-16 12:14 UTC by DenisNosnitsin1970

New record.

2022-08-16 14:20 UTC, thea-m requested changes

2022-08-16 14:20 UTC, thea-m commented on ParisBNF/abb/BNFabb216.xml
> +            <title>A short grammair of Ethiopic, A treatise on the Ethiopian qǝne-poetry by Giusto da Urbino</title>
grammar

2022-08-16 14:20 UTC, thea-m commented on ParisBNF/abb/BNFabb216.xml
> +                            <title type="complete" ref="STU0006Abrege">A short grammare of Ethiopic written by Giusto da Urbino in 1850-1854</title>
grammar

2022-08-16 14:40 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb216.xml
> +            <title>A short grammair of Ethiopic, A treatise on the Ethiopian qǝne-poetry by Giusto da Urbino</title>
ok.

2022-08-16 14:40 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb216.xml
> +                            <title type="complete" ref="STU0006Abrege">A short grammare of Ethiopic written by Giusto da Urbino in 1850-1854</title>
Ok, thanks!

2022-08-17 09:33 UTC, eu-genia approved these changes

2022-08-17 09:33 UTC, merged