Update BNFabb114.xml
BetaMasaheft/Manuscripts pull request #1812
Opened 2022-08-16 16:29 UTC by GueshSol

2022-08-16 21:03 UTC, DenisNosnitsin1970 requested changes
Two things: 1) miniatures are usually are described under "Decoration", according to my knowledge. 2) Are all miracles identified? I see that the description stops at fol. 18r, while the ms encompas many more leaves.  "Pricking and ruling" needs a formula. "Binding" also should be described.

2022-08-18 11:08 UTC, thea-m requested changes
Thank you, Guesh! This is already excellent work. All items are identified correctly and the msItems are all nested correctly. There are only a few small mistakes regarding the folio numbers, due to copy pasting. Can you correct them on the same branch and then commit again?

2022-08-18 11:08 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                        <locus from="11va" to="14r"/>
`  <locus from="12va" to="14r"/>`

2022-08-18 11:08 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           <locus from="11va" to="13rb"/>
<locus from="12va" to="13rb"/>

2022-08-18 11:08 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           <locus target="'#14r"/>
not the erroneous ' before #
`   <locus target="#14r"/>`

2022-08-18 11:08 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           <locus from="11va" to="13rb"/>
`    <locus from="14va" to="15ra"/> `

2022-08-18 11:08 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           <locus target="'#15v"/>
`   <locus target="#15v"/>`

2022-08-18 11:08 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                        <locus from="14va" to="15v"/>
` <locus from="16ra" to="18r"/>`

2022-08-18 11:08 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           <locus from="16ra" to="18r"/>
`<locus from="16ra" to="16vb"/> `

2022-08-18 11:08 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           <locus target="'#16vb"/>
`  <locus target="#16vb"/>`

2022-08-18 11:09 UTC, thea-m commented
@DenisNosnitsin1970 : You are right, the description is not complete. We are doing it step by step to practice the PR workflow.

2022-08-18 12:04 UTC, thea-m approved these changes
Very good!

2022-08-18 12:05 UTC, merged