Stubfor cambridge bfbs171
BetaMasaheft/Manuscripts pull request #1826
Opened 2022-08-29 10:36 UTC by karljonaskarlsson

Created stub

2022-08-29 10:41 UTC, thea-m approved these changes
From the technical side, everything seems fine!

2022-08-30 08:14 UTC, SophiaD-M commented
Identifiers wrong - two different signatures, please change

2022-08-30 12:15 UTC, SophiaD-M commented on LondonBibleSociety/BSLet171.xml
> +         <langUsage><language ident="en">English</language></langUsage>
maybe add also Geez

2022-08-30 12:15 UTC, SophiaD-M requested changes

2022-08-30 12:15 UTC, SophiaD-M commented on LondonBibleSociety/BSLet171.xml
> +                     <idno>BFBS Mss 171</idno>
add all known alternative signatures

2022-08-31 10:52 UTC, SophiaD-M approved these changes

2022-08-31 10:52 UTC, merged