Create BSLet172.xml
BetaMasaheft/Manuscripts pull request #1827
Opened 2022-08-29 11:01 UTC by karljonaskarlsson

Created stub for BFBS 172

2022-08-29 11:08 UTC, thea-m requested changes
Thank you! Two small remarks

2022-08-29 11:08 UTC, thea-m commented on LondonBibleSociety/BSLet172.xml
> +         <langUsage><language ident="en">English</language></langUsage>
you use "gez" above, so it must be defined here:   `<language ident="gez">Gǝʿǝz</language>`

2022-08-29 12:50 UTC, thea-m approved these changes

2022-08-29 12:51 UTC, thea-m commented
The XML is fine, I won't merge these records until approved by a project member

2022-08-30 08:17 UTC, SophiaD-M commented
again two different identifiers for ms - please change

2022-08-30 08:54 UTC, thea-m commented
Thanks @SophiaD-M! Very crucial!

2022-08-30 09:06 UTC, SophiaD-M requested changes

2022-08-30 09:06 UTC, SophiaD-M commented on LondonBibleSociety/BSLet172.xml
> +   schematypens="http://purl.oclc.org/dsdl/schematron"?><TEI xmlns="http://www.tei-c.org/ns/1.0" xml:lang="en" xml:id="BSLet169" type="mss">
wrong identifier

2022-08-30 12:18 UTC, SophiaD-M approved these changes

2022-08-30 12:19 UTC, merged