BDLaethd22
BetaMasaheft/Manuscripts pull request #1840
Opened 2022-09-02 15:16 UTC by thea-m

Here's the letter :) See also remark at the top of the meeting agenda document, maybe not to be discussed in the PR.
It's not really good encoding to include the entire text in incipit, but I think that we'll want to print it, and it will probably be too difficult for me to visualise the content of the `<div type="edition"> `, so this is a workaround (it will be easier to substitute the word "Incipit" in such cases by something else).
A few questions are written in comments in the record.
Thank you!

2022-09-05 08:07 UTC, karljonaskarlsson requested changes

2022-09-05 08:07 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethd22.xml
> +                                        on the inside of the folder in which the letter is kept. Another sticker with estimated dating, ‘[109]’ (possibly an inventory number), and brief content descr
"content description signature" – is a word missing here?

2022-09-05 16:18 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethd22.xml
> +                                of the arrival of a cannon in <!--or from?--> <placeName ref="LOC2449Dalant"/>. It might be related to the events leading up to the siege of
I cannot say if the cannon came in or from Dalāntā. Perhaps we may consult Solomon or someone skilled in Amharic.

2022-09-27 09:32 UTC, thea-m commented
Can this be merged? I would add the open Amharic question to the overview table. Also for other manuscripts, I think we might need someone with better Amharic than us to have a look at some texts at the end.

2022-09-29 05:40 UTC, merged