Guesh 07 bnf abb 114
BetaMasaheft/Manuscripts pull request #1863
Opened 2022-09-20 14:40 UTC by GueshSol

2022-09-20 17:30 UTC, thea-m requested changes
Very good, Guesh! I made some comments regarding typos. 
And a general comment: I think that you copied the description from the Art Themes, which is fine, but be careful that the Art Themes describe the topic as an abstract, to be valid for all individual renderings it might receive in manuscripts. Here, you describe the concrete rendering of the Art Theme in this manuscript, so instead of describing what the miniatures look like "typically" you can describe how they actually look like here.

2022-09-20 17:30 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           carries him; third, in varying sequence Golgotha, Jerusalem, the mount of
the same is true for "varying" as for "typically": This only makes sense in the art theme, here, there must be one concrete sequence

2022-09-20 17:30 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                              corresp="AT1127MMQatir"/>typically with sequence of three
corresp="AT1127MMQatir"/>typically  space missing

2022-09-20 17:30 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           before Patriarch Zakārǝzās and showing him his leprosy; second, the
Zakārǝyās

2022-09-20 17:30 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           the bishop showing himself healed to patriarch Zakārǝzās; sixth, the bishop showing himself healed to his student ; and
Zakārǝyās

2022-09-20 17:30 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           episodes/events, showing: first, Sofyā lying on top of a building before
decide whether you want to use Sophia or Sofyā in the description

2022-09-20 17:30 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           cncerning his illness.
concerning

2022-09-20 17:30 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           who are attacking him; second, the monks preventing him for eating;
preventing him to eat?

2022-09-20 17:30 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           those he killed; Second the cannibal asking the peasant to sell his ox;
second

2022-09-20 17:30 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           let him free performing gesture of blessing; and fourth, the thief
a gesture of blessing, here and throughout

2022-09-20 17:30 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                        <desc> A miniature of the art theme <ref type="authFile"
It might make sense to state that these are depicted from bottom to top?

2022-09-20 17:59 UTC, GueshSol commented
Thank you @thea-m for your excellent remarks, yes I copied the sequence of description from the art themes and just adjusted them how the decorations are distributed in my manuscript in reality, and except for the first phrases after the authority files of the decorations that I added ''typically..'' the rest sequences are arranged in on the basis of the miniatures in the MS.

2022-09-21 15:43 UTC, thea-m requested changes
Thank you, wonderful, just some last minor remarks

2022-09-21 15:43 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                              corresp="AT1109MMWorker"/> with one two episodes, showing: first, the
"one two episodes" - is it one or two? :)

2022-09-21 15:43 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           varying sequence Golgotha, Jerusalem, the mount of Olives, Bethlehem and
please delete "in varying sequence"

2022-09-21 15:43 UTC, thea-m commented on ParisBNF/abb/BNFabb114.xml
> +                           of the amnsucript. They contain images of several saints, martyrs and
manuscript :)

2022-09-22 09:49 UTC, thea-m approved these changes

2022-09-22 09:49 UTC, merged