Ms 2002.4 guesh
BetaMasaheft/Manuscripts pull request #1902
Opened 2022-10-12 16:01 UTC by GueshSol

2022-10-13 11:59 UTC, thea-m requested changes
I think that everything is fine - I did not double check the IDs now, but all seems good. Only one remark in the last item. Thank you!

2022-10-13 11:59 UTC, thea-m commented on new/CIA20024.xml
> +                                <msItem xml:id="ms_i2.2.33">
This item is included in ms_i2.2.32, but numbered ms_i2.2.33: It should either be numbered ms_i2.2.32.4 or be moved outside of ms_i2.2.32. Both solutions would be fine, you have to decide which is conceptually better.

2022-10-17 09:59 UTC, thea-m approved these changes

2022-10-17 09:59 UTC, merged

2022-10-17 10:03 UTC, thea-m commented
@GueshSol note that I now moved this manuscript from the folder "new" to the folder "ChicagoIA"

2022-10-17 10:07 UTC, GueshSol commented
Thank you very much.

On Mon, Oct 17, 2022 at 12:03 PM thea-m ***@***.***> wrote:

> @GueshSol <https://github.com/GueshSol> note that I now moved this
> manuscript from the folder "new" to the folder "ChicagoIA"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Manuscripts/pull/1902#issuecomment-1280607703>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWGOX43RUXROXLDRYH45J63WDUP7TANCNFSM6AAAAAARDN4XPQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>