BDLaethg40
BetaMasaheft/Manuscripts pull request #1903
Opened 2022-10-14 13:49 UTC by thea-m

And the next scroll :)

2022-10-16 08:57 UTC, ElianaDalSasso approved these changes
Thank you Thea! I have just a minor doubt.

2022-10-16 08:57 UTC, ElianaDalSasso commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                                    <desc>Remains of writing and a drawing are visible on the upper part of the verso. Only single characters are legible anymore.
Is 'anymore' a typo?

2022-10-17 15:50 UTC, MassimoVilla requested changes
Thank you Thea!

2022-10-17 15:50 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                                ደዌ</hi><gap reason="illegible"/> ወትስቅሎ፡ ላዕሌሃ፡ ወይበቁዕ፡ በረድኤተ፡ እግዚአብሔር፡ ልዑል፡ ወክቡር፡
I would mark ወይበቁዕ፡ with `<sic/>`, the expected form should be ወይበቍዕ፡ (the scroll has indeed ወይበቁዕ)

2022-10-17 15:50 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                                <persName ref="PRS13861WalattaH" role="owner"><hi rend="rubric"><add place="below">ወለተ፡ ሕውየት</add></hi></persName></explicit>
Check ሕውየት: is it ሕይወት?

2022-10-17 15:50 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                                <persName ref="PRS13861WalattaH" role="owner"><hi rend="rubric"><add place="interlinear">ወለተ፡ ሕውየት</add></hi></persName></explicit>
Is ሕውየት: to be marked with `<sic/>` (also above)?

2022-10-18 09:25 UTC, thea-m commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                                <persName ref="PRS13861WalattaH" role="owner"><hi rend="rubric"><add place="below">ወለተ፡ ሕውየት</add></hi></persName></explicit>
both typos, thanks!

2022-10-18 09:25 UTC, thea-m commented
Thank you, Massimo!

2022-10-18 10:06 UTC, MassimoVilla approved these changes

2022-11-22 09:59 UTC, karljonaskarlsson requested changes
Sorry for the minor suggestions – I will make use of the editing functionality for the rest of the record (when suitable).

2022-11-22 09:59 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                                ዓይነናስ፡ ዓይነ፡ ዛር፡ ወዓይነ፡ ጠቢብ፡ ወቡዳ፡ ባርያ<supplied reason="omitted">፡</supplied> ወሌጌዎን፡ ድድቅ፡ ወጋኔነ፡ ቀትር፡ ምች፡ ወተላዋሽ፡
ወቡዳ፡ ዓይነ፡ ባርያ

2022-11-22 09:59 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                                ቁረኛ፡ ወተያያዥ፡ ዕጀ፡ ሰብእ፡ ወጽላወጌ፡ ደም፡ ወሽዐተላይ<supplied reason="omitted">፡</supplied>
ቁራኛ፡ ?
ወጽላወጊ፡ ?
ወሽተላይ

2022-11-22 09:59 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                                <del rend="expunctuated">ወ</del>ወቀተለቶ፡ ለወልዳ፡ ወበከየት፡ እሙ፡ ወይቤላ፡ ኦብእሲቶ፡ ምንት፡ ያበከየኪ፡</incipit>
either ያበክየኪ፡ or, if the present form is kept, add sic?

2022-11-22 09:59 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                            <explicit xml:lang="gez" type="supplication">ኦአምላከ፡ ቅዱስ፡ ሱስንዮስ፡ አድኅና፡ እምሕማመ፡ ዓይነጥላ፡ ወዓይነናስ፡ ወዓይነናስ፡ ዓይነ፡ ዘር፡ ወውላጅ፡ ዓይነጠቢብ፡ ወቡዳ፡
Omit one ወቡዳ፡

2022-11-22 09:59 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                            <explicit xml:lang="gez">ወትቤ፡ ይእቲ፡ አንሰ፡ ኢየኃውር፡ ኀበ፡ ሀሎ፡ ስምከ፡ ፍኖተ፡ ውስቴታ፡ ወኢይቀርብ፡ ኀበ፡ ሀሎ፡ ስምከ፡ ፍኖተ፡ ወይፀውራ፡
ወኀበ፡ ይፀውራ፡

2022-11-22 09:59 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                            ወቡዳ፡ ዓይነ፡ ባርያ<surplus>ያ</surplus>፡ ወሌጌዎን፡ ድድቅ፡ ወጋኔነ፡ ቀትር፡ ምች፡ ወተላኖሽ፡ ቁረኛ፡ ወተያይዦ፡ ደ፡
ወተላዋሽ፡
ቁራኛ፡ ?
ወተያያዥ፡
ደም

2022-11-22 09:59 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                            ወሸተላይ፡ መገኛ፡ ወጕሥምት፡ ውጋት፡ ወቁርጥማት፡ ፍልሸት፡ ሥራይ፡ ወድግምት፡ ወቁርጸት፡ ፌራ፡ ዘደጋ፡ ንዳድ፡ ዘቆላ፡ ወእምኵሉ፡ ደዌያት፡
ፍልጸት፡
ገዳድ፡ ?

2022-11-22 10:22 UTC, karljonaskarlsson requested changes

2022-11-22 10:22 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                            ወሶበ፡ ርዕዩ፡ መልክዓ፡ ብእሲት፡ ዓራጊት፡ እንተ፡ ትነብ</hi>ር፡ በማዕዶተ፡ ፈለግ፡</incipit>
ኀራጊት፡

2022-11-22 10:22 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                            <explicit xml:lang="gez">አድኅና፡ እምሕማመ፡ ደም፡ ወሾተላይ፡ ለዓመተ፡ እግዚአብሔር<supplied reason="omitted">፡</supplied>
No word divider after እምሕማመ

2022-11-22 10:22 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                                ወአፅገዕ፡ ፍሬ፡ ማኅፀና፡
ወአፅግዕ፡ ?

2022-11-22 10:22 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethg40.xml
> +                                ተላይ፡ ማሎክ፡ ሉሎክ፡ አፍላሎክ፡ በእለ፡ አስማቲከ፡ ዘአንሳእከ፡ ለዓልአዛር፡ እም<gap reason="illegible"/>ሰ፡ መቃብር፡ ከማሁ፡
በእሉ፡ ?

2022-11-22 12:40 UTC, thea-m commented
Thank you Jonas, I carried out the corrections

2022-12-22 15:23 UTC, merged