Ber or fol117 corr mk
BetaMasaheft/Manuscripts pull request #1909
Opened 2022-10-24 19:08 UTC by MarcinKrawczuk

2022-10-25 11:10 UTC, thea-m requested changes
Thank you, just some small things

2022-10-25 11:10 UTC, thea-m commented on Berlin/BerOrFol117.xml
> +<note>Indication for reading: <q xml:lang="gez">አመ፫፡ ለተኅሣሥ፡</q></note>
I think that here, `<foreign>` should be used, `<q> `is only for additions

2022-10-25 11:10 UTC, thea-m commented on Berlin/BerOrFol117.xml
> +</support>
Could you give the number of leafs and their extent in the composite manuscript, and also information on foliation (if available)? In composite manuscripts, I find this always really helpful to get an impression of the structure.

2022-10-25 11:10 UTC, thea-m commented on Berlin/BerOrFol117.xml
> +<note>The note states that the manuscript was sent by a monk <persName ref="PRS13893Mahyawi">Maḥyawi ʾƎgziʾ</persName> to <placeName ref="LOC3957Jerusa">Jerusalem</placeName>.</note>
It is better to move this information inside `<desc>`, then note can be deleted

2022-10-25 18:55 UTC, MarcinKrawczuk commented
Thank you, I hope it's better now regarding the pagination, also I added
one more note and a bit of info on rubrication

wt., 25 paź 2022 o 13:10 thea-m ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
>
> Thank you, just some small things
> ------------------------------
>
> In Berlin/BerOrFol117.xml
> <https://github.com/BetaMasaheft/Manuscripts/pull/1909#discussion_r1004342437>
> :
>
> > +<foliation>There is foliation provided in the upper right corner of each folio.</foliation>
>
> +</supportDesc>
>
> +</objectDesc>
>
> +</physDesc>
>
> +
>
> +</msPart>
>
> +
>
> +<msPart xml:id="p2">
>
> +  <msIdentifier></msIdentifier>
>
> +  <msContents>
>
> +
>
> +<msItem xml:id="p2.1">
>
> +<locus from="1" to="26"/>
>
> +<title xml:lang="en" type="complete" ref="LIT6187Dersan3Tahsas">Homily for the 3rd of Tāḫśāś on the birth of Mary, her presentation in the Temple,
>
> +  marriage to Joseph and visit to Zacharias and Elizabeth</title>
>
> +<note>Indication for reading: <q xml:lang="gez">አመ፫፡ ለተኅሣሥ፡</q></note>
>
>
> I think that here, <foreign> should be used, <q> is only for additions
> ------------------------------
>
> In Berlin/BerOrFol117.xml
> <https://github.com/BetaMasaheft/Manuscripts/pull/1909#discussion_r1004344714>
> :
>
> > +
>
> +<msItem xml:id="p2.23">
>
> +<locus from="427" to="482"/>
>
> +<title type="complete" xml:lang="en" ref="LIT2487Vision">Homily by Theophilus of Alexandria on the flight of Holy Family to Egypt</title>
>
> +<textLang xml:lang="gez"></textLang>
>
> +<note>Indication for reading: <q xml:lang="gez"></q></note>
>
> +</msItem>
>
> +
>
> +  </msContents>
>
> +
>
> +<physDesc>
>
> +<objectDesc form="Codex">
>
> +<supportDesc>
>
> +<support>
>
> +<material key="parchment"/>
>
> +</support>
>
>
> Could you give the number of leafs and their extent in the composite
> manuscript, and also information on foliation (if available)? In composite
> manuscripts, I find this always really helpful to get an impression of the
> structure.
> ------------------------------
>
> In Berlin/BerOrFol117.xml
> <https://github.com/BetaMasaheft/Manuscripts/pull/1909#discussion_r1004345597>
> :
>
> > +<decoNote type="miniature" xml:id="d1">
>
> +<locus target="#257"/>
>
> +<desc>A moderately stylized representation of the <term key="cross">cross</term>.</desc>
>
> +</decoNote>
>
> +</decoDesc>
>
> +
>
> +<additions>
>
> +
>
> +<list>
>
> +
>
> +<item xml:id="a1">
>
> +<desc type="OwnershipNote"></desc>
>
> +<q xml:lang="gez">በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ። በአኰቴተ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ዛቲ፡ መጽሐፍ፡ ተፈነወት፡ እም፡ ሐበ፡ ማኅየዊ፡ እግዚእ፡ ፈላሲ፡
>
> +ትብጻሕ፡ ኢየሩሳሌም፡ ለእመ፡ በጸሕኩ፡ ነፍስየ፡ እብእ፡ ወለእመ፡ ኢበጸሕኩ፡ አነ፡ እለ፡ ብጽሑ፡ ያብእዋ፡ ወእለ፡ ኮኑ፡ ቀሲሳን፡ ለዛቲ፡ መካን፡ ከመ፡ ይዘክሩኒ፡ እመኒ፡ ሞትኩ፡
>
> +ወእመኒ፡ ሐየውኩ፡ ሰላም፡ ለክሙ፡ ወበጸሎትክሙአ፡ ኢትርስዕኒ።</q>
>
> +<note>The note states that the manuscript was sent by a monk <persName ref="PRS13893Mahyawi">Maḥyawi ʾƎgziʾ</persName> to <placeName ref="LOC3957Jerusa">Jerusalem</placeName>.</note>
>
>
> It is better to move this information inside <desc>, then note can be
> deleted
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Manuscripts/pull/1909#pullrequestreview-1154603114>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJULQ7NOJFZ3GYMEZVTWE6525ANCNFSM6AAAAAARNIQLOE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-26 07:17 UTC, thea-m approved these changes
Thank you!

2022-10-26 07:17 UTC, merged

2022-10-26 20:46 UTC, eu-genia commented
note that the merged file does not validate; it has an old file and master branch version as the basis and the git was not rebased before the push. work is needed here. i suggest that the push is reverted so that we do not have problematic files and then resubmitted.

all old branches created before the new validation has been put in place should be treated with care and preferably rebased before merging

2022-10-26 20:48 UTC, eu-genia commented
PS there is of course no problem in working with Berlin manuscripts if these are needed for personal research / other projects, but they are not a Bm priority as the Qalamos project is supposed to be processing existing catalogues of mss in German libraries

2022-10-26 20:51 UTC, eu-genia commented
as far as I can see the main problem is the xml:id of msItems (should be `p1_i1 `not `p1.i1` etc)
Thank you!

2022-10-26 21:17 UTC, MarcinKrawczuk commented
So should I do a modification and correct  p1.i1 into  p1_i1 etc.?

śr., 26 paź 2022 o 22:52 Eugenia ***@***.***> napisał(a):

> as far as I can see the main problem is the xml:id of msItems (should be p1_i1
> not p1.i1 etc)
> Thank you!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Manuscripts/pull/1909#issuecomment-1292639127>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJRHRCCN74N36ZIHZGLWFGKXPANCNFSM6AAAAAARNIQLOE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-26 21:34 UTC, eu-genia commented
whatever it takes to have the file valid, I did not check if there  were more validation errors. thank you

2022-10-26 21:35 UTC, eu-genia commented
(please create a new branch)

2022-10-27 22:39 UTC, eu-genia commented
fixed now https://github.com/BetaMasaheft/Manuscripts/pull/1916