Max 15
BetaMasaheft/Manuscripts pull request #1946
Opened 2022-12-10 17:56 UTC by MassimoVilla

Dear all, here comes MS BDLaethd16, an 18th-cent. splendidly (to my unprofessional eye) illuminated manuscript of poetry.
Of course, I just gave some basic info on the binding: Eliana will provide a more thorough description of these features. I've completely left the decoDesc to Jacopo.

2022-12-12 10:03 UTC, thea-m requested changes
Thank you, great!
I wonder whether it might be useful to very summarily describe the text/image layout explicitly in one sentence, maybe in layout or decorations? Right now, I'm not sure that someone who reads only the description would be able to reconstruct it.

2022-12-12 14:20 UTC, ElianaDalSasso requested changes
Thank you Massimo! It a really interesting manuscript to my eyes as well :)
I have just two minor comments.

2022-12-13 14:22 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethd16.xml
> +                                    of <locus target="#1va"/>.  Clues for the rubricator are found on the left margin of <locus from="2ra" to="4ra"/>.
Yes, exactly!

2022-12-13 14:28 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethd16.xml
> +                                    Some leaves stains of unspecified nature (e.g. <locus target="#33v #34r #35v"/>).
Thank you Eliana! I have added these observations in the condition section.

2022-12-13 15:45 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethd16.xml
> +                               eventually purchased by <persName ref="PRS5782JuelJen"/> at an auction at Sotheby's on 20 March 1983, according to the auction catalogue.
Exactly, thank you! I've created the Person record and added a note within History

2022-12-13 17:34 UTC, ElianaDalSasso approved these changes

2022-12-14 13:05 UTC, gnizla commented
> Thank you, great! I wonder whether it might be useful to very summarily describe the text/image layout explicitly in one sentence, maybe in layout or decorations? Right now, I'm not sure that someone who reads only the description would be able to reconstruct it.

Hello @thea-m I could include this in the opening description of the decorations

2022-12-14 13:16 UTC, MassimoVilla commented
> > Thank you, great! I wonder whether it might be useful to very summarily describe the text/image layout explicitly in one sentence, maybe in layout or decorations? Right now, I'm not sure that someone who reads only the description would be able to reconstruct it.
> 
> Hello @thea-m I could include this in the opening description of the decorations

I have added a short sentence in the layout section, inside `<note corresp="#textarea2 #margin2">`. We can discuss if it is more appropriate here or in the decoDesc part.

2022-12-16 16:12 UTC, thea-m approved these changes

2023-01-03 10:46 UTC, MassimoVilla commented
Do you think we can merge this branch (and Max14)? I am afraid that, over time, the likelihood of having conflicting branches will increase

2023-05-02 18:04 UTC, gnizla approved these changes

2023-05-03 13:04 UTC, merged