Dr 22 12 sinai et003
BetaMasaheft/Manuscripts pull request #1955
Opened 2022-12-22 13:14 UTC by thea-m

2022-12-22 13:15 UTC, eu-genia approved these changes

2022-12-25 22:58 UTC, DenisNosnitsin1970 requested changes

2022-12-25 22:58 UTC, DenisNosnitsin1970 commented on SinaiStCatherine/SinaiEt003.xml
> +                <idno>Sinai Ethiopic 3</idno>
No indication to online resource?

2022-12-25 22:58 UTC, DenisNosnitsin1970 commented on SinaiStCatherine/SinaiEt003.xml
> +                         <ab type="ruling">Ruling and pricking are visible.</ab>
Wouldn't it be better to split the into into "ruling" and "pricking"?

2022-12-25 22:58 UTC, DenisNosnitsin1970 commented on SinaiStCatherine/SinaiEt003.xml
> +                     <handNote xml:id="h1" script="Ethiopic">
I do it slightly differently, it would be good to unify at least in this collection.

2022-12-25 22:58 UTC, DenisNosnitsin1970 commented on SinaiStCatherine/SinaiEt003.xml
> +                   <origDate notBefore="1700" notAfter="1899" evidence="lettering"/>
Why is here 1700, not 1800, as it seems to follow from the hand description.

2023-01-02 13:09 UTC, DenisNosnitsin1970 approved these changes

2023-01-02 13:21 UTC, merged