Bn fabb62
BetaMasaheft/Manuscripts pull request #1989
Opened 2023-01-16 18:42 UTC by MarcinKrawczuk

This is a very basic description because I only need it for the ID: https://github.com/BetaMasaheft/Documentation/issues/2293
Please notice that the xml:id is different than the file name - is that a problem?

2023-01-19 10:49 UTC, eu-genia commented
xml:id may not be different from the filename

2023-01-19 10:55 UTC, eu-genia requested changes

2023-01-19 10:55 UTC, eu-genia commented on ParisBNF/abb/BNFabb62and63.xml
> +type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?><TEI xmlns="http://www.tei-c.org/ns/1.0" type="mss" xml:lang="en" xml:id="BNFabb62">
change ID to BNFabb62and63 or file name to BNFabb62 (whichever way but they MUST be the same)

2023-01-19 10:55 UTC, eu-genia commented on ParisBNF/abb/BNFabb62and63.xml
> +               </msIdentifier>
add `idno `and put 62 and 63 for the entire unit

2023-01-19 10:55 UTC, eu-genia commented on ParisBNF/abb/BNFabb62and63.xml
> +  <extent></extent>
` <measure unit="leaf">226</measure>` ?

2023-01-19 10:55 UTC, eu-genia commented on ParisBNF/abb/BNFabb62and63.xml
> +
we usually have some physDesc for the entire codex here, e.g. library binding would be interesting

2023-01-20 18:09 UTC, MarcinKrawczuk commented
Thank you, I hope it's better now.

czw., 19 sty 2023 o 11:55 Eugenia ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In ParisBNF/abb/BNFabb62and63.xml
> <https://github.com/BetaMasaheft/Manuscripts/pull/1989#discussion_r1081098387>
> :
>
> > @@ -0,0 +1,212 @@
>
> +<?xml version="1.0" encoding="UTF-8"?><?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/Schema/master/tei-betamesaheft.rng"
>
> +schematypens="http://relaxng.org/ns/structure/1.0"?><?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/Schema/master/tei-betamesaheft.rng"
>
> +type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?><TEI xmlns="http://www.tei-c.org/ns/1.0" type="mss" xml:lang="en" xml:id="BNFabb62">
>
>
> change ID to BNFabb62and63 or file name to BNFabb62 (whichever way but
> they MUST be the same)
> ------------------------------
>
> In ParisBNF/abb/BNFabb62and63.xml
> <https://github.com/BetaMasaheft/Manuscripts/pull/1989#discussion_r1081098956>
> :
>
> > +            <pubPlace>Hamburg</pubPlace>
>
> +            <availability>
>
> +               <licence target="http://creativecommons.org/licenses/by-sa/4.0/">
>
> +                  <p>This file is licensed under the Creative Commons Attribution-ShareAlike 4.0. </p>
>
> +               </licence>
>
> +            </availability>
>
> +         </publicationStmt>
>
> +         <sourceDesc>
>
> +            <msDesc xml:id="ms">
>
> +
>
> +               <msIdentifier>
>
> +                  <repository ref="INS0303BNF"/>
>
> +                  <collection>Manuscrits orientaux</collection>
>
> +                  <collection>Fonds éthiopien</collection>
>
> +                  <collection>d'Abbadie</collection>
>
> +               </msIdentifier>
>
>
> add idno and put 62 and 63 for the entire unit
> ------------------------------
>
> In ParisBNF/abb/BNFabb62and63.xml
> <https://github.com/BetaMasaheft/Manuscripts/pull/1989#discussion_r1081099912>
> :
>
> > +         </publicationStmt>
>
> +         <sourceDesc>
>
> +            <msDesc xml:id="ms">
>
> +
>
> +               <msIdentifier>
>
> +                  <repository ref="INS0303BNF"/>
>
> +                  <collection>Manuscrits orientaux</collection>
>
> +                  <collection>Fonds éthiopien</collection>
>
> +                  <collection>d'Abbadie</collection>
>
> +               </msIdentifier>
>
> +
>
> +<physDesc>
>
> +
>
> +  <objectDesc form="Codex">
>
> +<supportDesc>
>
> +  <extent></extent>
>
>
> <measure unit="leaf">226</measure> ?
> ------------------------------
>
> In ParisBNF/abb/BNFabb62and63.xml
> <https://github.com/BetaMasaheft/Manuscripts/pull/1989#discussion_r1081100851>
> :
>
> > +                  <p>This file is licensed under the Creative Commons Attribution-ShareAlike 4.0. </p>
>
> +               </licence>
>
> +            </availability>
>
> +         </publicationStmt>
>
> +         <sourceDesc>
>
> +            <msDesc xml:id="ms">
>
> +
>
> +               <msIdentifier>
>
> +                  <repository ref="INS0303BNF"/>
>
> +                  <collection>Manuscrits orientaux</collection>
>
> +                  <collection>Fonds éthiopien</collection>
>
> +                  <collection>d'Abbadie</collection>
>
> +               </msIdentifier>
>
> +
>
> +<physDesc>
>
> +
>
>
> we usually have some physDesc for the entire codex here, e.g. library
> binding would be interesting
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Manuscripts/pull/1989#pullrequestreview-1261549767>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJV74AV76R3FVJKY2C3WTEMTZANCNFSM6AAAAAAT5BL7GM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-20 18:21 UTC, eu-genia approved these changes

2023-01-20 23:42 UTC, merged