Addisie md dl002
BetaMasaheft/Manuscripts pull request #2003
Opened 2023-02-02 13:26 UTC by thea-m

@Addisie has a technical problem logging in into GitHub due to 2fA while in Ethiopia. She has done the description and will read and act on all comments and corrections. (I am just the messenger)

2023-02-02 14:55 UTC, eu-genia commented
Thank you @Addisie !
Maybe @Mersha-Alehegne will be able to provide some of the missing metadata.
I have checked and it is the file that had been previously shared  (as PDF) with the HLCEES, at that time the folder name was "Mamher Demisse"
Now thaI assume, as discussed with @Mersha-Alehegne , that the abbreviation MD stands actually for Mamher Deggu https://hviewer.bl.uk/IamsHViewer/Default.aspx?mdark=ark:/81055/vdc_100023431294.0x000001&_ga=2.108858306.1304144530.1586083190-448041624.1571936776
, a collection photographed for EAP. Yet unfortunately this particular MS does not seem to be among the ones listed at the EAP (or submitted), as far as I could check, and it is not present in the metadata spreadsheet that I received from @Mersha-Alehegne  either.

2023-02-02 14:56 UTC, eu-genia commented on new/MDDL002.xml
> +                                   <note>Measurements of the manuscript's dimensions were not provided in the manuscript's metadata and images.</note>
maybe dimensions can be estimated using the paper ruler photographed together with the MS

2023-02-03 10:59 UTC, eu-genia commented on new/MDDL002.xml
> +                                   <note>Measurements of the manuscript's dimensions were not provided in the manuscript's metadata and images.</note>
I have now used https://imagemeasurement.online/ applying the scale provided and can give the 

outer measurements
height: 326 mm
width: 286 mm

text area (f. 5r)
height: 205 mm
width: 215 mm

2023-02-03 11:06 UTC, eu-genia requested changes

2023-02-03 11:06 UTC, eu-genia commented on new/MDDL002.xml
> +                                </item>
maybe the title on the mahdar (አፈወርቅ፡) should also be listed as an e7 or in the binding description

2023-02-03 11:06 UTC, eu-genia commented on new/MDDL002.xml
> +            <editionStmt><p>Digitized and catalogued within the framework of the project Documenting an
this probably has to be changed, as the MS was digitized much earlier, within the framework of EAP336 project - but it was not submitted among the EAP mss, so I am not sure; possibly we should simply write that it was digitized by @Mersha-Alehegne @MershaMengistie in 2010-2011 and catalogued within the framework of the ʾAbǝnnat Tǝmhǝrt project

2023-02-09 13:56 UTC, eu-genia commented on new/MDDL002.xml
> +                                        <height>326 </height>
please remove the blank space after 326

2023-02-09 13:58 UTC, thea-m commented
Thank you @eu-genia for the comments and the helpful measuring tool, I did not know about it

2023-02-09 14:00 UTC, eu-genia approved these changes

2023-03-03 14:32 UTC, merged

2023-03-04 04:56 UTC, MershaMengistie commented
I have one suggesion Zhenia: until I come and clarify the problems with the EAP 336 mss, Addisie can work with the recently documented mss as they are not complicated like the ones on the table. Of course the older ones should also be finalized but later.  Just a suggestion.