Binding desc 5/5
BetaMasaheft/Manuscripts pull request #2007
Opened 2023-02-06 15:37 UTC by ElianaDalSasso

Dear all,
these are the last descriptions of the bindings of Juel-Jensen manuscripts. 
I decided to describe the condition of manuscripts composed of several msPart (f. 30, b. 6, b. 3) under a general element condition because the descriptions refer to the manuscript as a whole. In the single msParts, I only left a comment on the state of preservation (good/deficient).
On the contrary, I kept separated the descriptions of holes and tears on the writing support (except in b. 3 where the different msPart are not encoded yet).
Let me know what you think!

In the case you agree, I have to check if this approach has been applied consistently.

Thank you!
Eliana

2023-02-07 11:56 UTC, thea-m requested changes
Thank you! I agree with your general proposal regarding the distribution of information in composite manuscripts. Just some minimal remarks here

2023-02-08 13:31 UTC, thea-m approved these changes

2023-02-09 09:17 UTC, MassimoVilla requested changes
Thank you Eliana for your very rich descriptions! I just have minimal observations.
I agree with your subdivision for the composite MSS: it is the best way to discriminate between features of the whole codex and features of the single parts.

2023-02-09 09:17 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethf30.xml
> +                                  <!--the stains could be the result of oxidation of the parchment support
In my view we can also incorporate this comment in the text, for example "Dark red stains on ..., possibly due to oxidation of the support"

2023-02-09 09:17 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethf30.xml
> +                                The boards and the cover are possibly contemporary with most of the manuscript content.</p>
I would say "possibly contemporary with the main texts" (which recalls the hierarchy adopted in the textual part)

2023-02-09 09:17 UTC, MassimoVilla commented on OxfordBodleian/Juel-Jensen/BDLaethg33.xml
> +                                    The upper board is narrower than the book block. It has broken and lost part of the outer edge.
has been broken o is broken?

2023-04-04 07:35 UTC, MassimoVilla approved these changes

2023-05-02 18:03 UTC, gnizla approved these changes

2023-06-16 14:53 UTC, merged