Bn fabb80 corr mk 6 feb23
BetaMasaheft/Manuscripts pull request #2009
Opened 2023-02-07 20:40 UTC by MarcinKrawczuk

Some changes after a closer scrutiny of the ms.

2023-02-08 09:59 UTC, thea-m requested changes
Thank you! Just one minor remark

2023-02-08 09:59 UTC, thea-m commented on ParisBNF/abb/BNFabb80.xml
> +                                <title type="incomplete" ref="LIT6443Sunday6"/>
It can stay like this, but it is always helpful for the readers to have a short `<note>` in which the character of the incompleteness is indicated.

2023-02-08 18:57 UTC, MarcinKrawczuk commented
Of course, added a note. Thank you!

śr., 8 lut 2023 o 10:59 thea-m ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
>
> Thank you! Just one minor remark
> ------------------------------
>
> In ParisBNF/abb/BNFabb80.xml
> <https://github.com/BetaMasaheft/Manuscripts/pull/2009#discussion_r1099906066>
> :
>
> > @@ -96,84 +101,95 @@ type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
>                              </msItem>
>
>                              <msItem xml:id="ms_i1.10">
> -                                <locus from="39r" to="51v"/>
> -                                <title type="complete" ref="LIT6443Sunday6"/>
> +                                <locus from="39r" to="39v"/>
> +                                <title type="incomplete" ref="LIT6443Sunday6"/>
>
> It can stay like this, but it is always helpful for the readers to have a
> short <note> in which the character of the incompleteness is indicated.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Manuscripts/pull/2009#pullrequestreview-1288835341>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJSWY66GKXDPDAVPERDWWNVATANCNFSM6AAAAAAUUN2VQA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-09 11:46 UTC, thea-m approved these changes

2023-02-09 11:47 UTC, merged