Update BDLaethd17.xml
BetaMasaheft/Manuscripts pull request #2078
Opened 2023-04-21 12:57 UTC by gnizla

Very small deco note, but note that I am proposing to shift not before dating from 1500 to 1650-1750 based on style of headband.

2023-04-21 13:28 UTC, thea-m requested changes
Excellent, thank you! I have of course nothing against the dating, on which I trust you completely (and I am very happy that this narrows the estimated date of production of the manuscript). I would like to propose to adapt the wording inside `<history>` slightly to reflect that the main evidence for this timespan is the frame, not the handwriting ("Based on the style of the decorative frame on f. ..., the date of production can be set to..." or whatever you find good). I think that being clear about the dating evidence is methodologically significant and interesting for readers. Thanks again :)

2023-04-21 13:28 UTC, thea-m commented on OxfordBodleian/Juel-Jensen/BDLaethd17.xml
> +                      of Lasta around <date>1700</date> by the manuscript's former owner <bibl><ptr target="bm:1977Juel-Jensen"/></bibl>
bibliographic reference between parantheses?

2023-04-21 14:01 UTC, closed without merging

2023-04-29 09:34 UTC, ElianaDalSasso reviewed
Thank you Jacopo! Really interesting, I have just a minor comment.

2023-04-29 09:34 UTC, ElianaDalSasso commented on OxfordBodleian/Juel-Jensen/BDLaethd17.xml
> +                            be a period between the mid-seventeenth to mid-eighteenth century. The name of <persName
-can and the frame....be a period
Should 'can' be shifted close to 'be'?