Tweed Scrolls
BetaMasaheft/Manuscripts pull request #2153
Opened 2023-07-12 08:36 UTC by Ralph-Lee-UK

Corrected formatting issues with EMIPms00469 facsimile and text files. This request seeks to resolve conflicts in a previous pull request yesterday.

2023-07-12 08:37 UTC, Ralph-Lee-UK commented
The conflict in yesterday's pull request is now resolved, following Eugenia's advice.

2023-07-12 13:22 UTC, thea-m requested changes
Thank you!

2023-07-12 13:22 UTC, thea-m commented on EMIP/magicscrolls/EMIPms00469/transkribusTextEMIPms00469.xml
> +               <lb facs="#facs_1_line_1656341948235_22" n="1" break="no"/>በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱ<lb facs="#facs_1_r1l12" n="2" break="no"/>ሽስAsk Ralph about this፡ ፩አምላክ፡ ጸሎትMy change፡ በእንተ፡ አው<lb f
"ሽስAsk Ralph about this፡ ፩አምላክ፡ ጸሎትMy change፡" These seem to be comments maybe not intended for the final version? Also "My change" below

2023-07-12 14:20 UTC, Ralph-Lee-UK reviewed
Indeed, I will review these in further transcriptions if the formatting now works. Thanks for this. @thea-m I think I have done what I need to accept your suggestions!

2023-07-14 07:21 UTC, Ralph-Lee-UK reviewed
@thea-m I believe I have removed the comments now

2023-07-14 07:35 UTC, thea-m approved these changes
Thank you!

2023-07-14 07:35 UTC, merged