Dr 23 11 sinai new et002
BetaMasaheft/Manuscripts pull request #2190
Opened 2023-10-25 15:06 UTC by thea-m

Some questions are in the comments. The text of the addition is partly still not understandable to me (maybe it is not all Geez). I didn't suggest yet a date for the hand (my feeling is rather the beginning of the period in question, but I leave it to you)

2023-10-25 19:59 UTC, DenisNosnitsin1970 requested changes

2023-10-25 19:59 UTC, DenisNosnitsin1970 commented on SinaiStCatherine/SinaiNewEt002.xml
> +                         <!--create person IDs?-->
But what is the language? The note is not understandable. Please reflect this in the note.

2023-10-25 19:59 UTC, DenisNosnitsin1970 commented on SinaiStCatherine/SinaiNewEt002.xml
> +                        <decoNote xml:id="b1">Islamic binding, boards of paper or cardboard covered with blind-tooled leather, with flap. A small leather strip is inserted into the hole in the flap.<
Perhaps, we should cautiously say: "Non-Ethiopian binding"

2023-10-25 19:59 UTC, DenisNosnitsin1970 commented on SinaiStCatherine/SinaiNewEt002.xml
> +                       <decoNote xml:id="b2" type="Cover">Blind-tooled brown leather cover.</decoNote>
If you look closer, you will see that the multiple rosettes have the same decorativ motif inside, smth like bird (cock?)

2023-10-25 19:59 UTC, DenisNosnitsin1970 commented on SinaiStCatherine/SinaiNewEt002.xml
> +                         <desc type="Unclear">Note in the upper margin, partly incomprehensible.</desc>
I would like to have a look at the notes, I would need the numbers of images, to come through recto - verso sets :)

2023-10-26 14:26 UTC, thea-m commented on SinaiStCatherine/SinaiNewEt002.xml
> +                         <ab type="ruling">The upper line is written above the ruling.</ab>
I gave examples. In general, I find the horizontal ruling more visible on the verso than on the recto

2023-10-26 14:26 UTC, thea-m commented on SinaiStCatherine/SinaiNewEt002.xml
> +                        the vowel markers of <foreign xml:lang="gez">ዝ</foreign> and <foreign xml:lang="gez">ት</foreign> are attached to the body of the character diagonally (<locus target="#2r"/>).
ስ is written differently on f. 1r (rather two lines) and 1v and 110v-111r (one curved line). Maybe the hand is not the same? My impression was that it was one hand (see lo and tu, for example), but that might be wrong. The ink also seems to be different.

2023-10-27 07:44 UTC, eu-genia commented
nb the file is not yet valid (I am sure you know)

2023-10-27 10:54 UTC, thea-m commented
Thank you, yes, it waited for the merging of person PR, done now

2023-10-31 09:53 UTC, merged