BMLacq784
BetaMasaheft/Manuscripts pull request #2204
Opened 2023-11-30 13:22 UTC by CarstenHoffmannMarburg

I updated the record of BMLacq784 according to Marrassini's catalogue. 

In ms_i2 I encoded several ethnic names as ሸንቀላ, አገው, አምሀራ, ትግራይ as ethnic or place names. Even though this is a magical text, I think they are used as ethnic names rather than demon names. I would also like to create new IDs for ትርኵ and ቅማንት and eventually also for ቦላ, which, according to my exploration, do not yet exist.

<img width="430" alt="Screenshot 2023_Turk" src="https://github.com/BetaMasaheft/Manuscripts/assets/40291787/bd576b71-31e2-423e-bccf-d0bebb7ace05">

2023-12-01 22:23 UTC, eu-genia requested changes

2023-12-01 22:23 UTC, eu-genia commented on FlorenceBML/BMLacq784/BMLacq784.xml
> +                            <title>Magical Prayer</title>
LIT6609ProtectPrayer?

2023-12-05 09:11 UTC, CarstenHoffmannMarburg commented on FlorenceBML/BMLacq784/BMLacq784.xml
> +                            <title>Magical Prayer</title>
Yes, thank you!

2023-12-05 12:30 UTC, thea-m requested changes
Thank you, great!

2023-12-05 13:39 UTC, CarstenHoffmannMarburg commented on FlorenceBML/BMLacq784/BMLacq784.xml
> +                                    <measure unit="leaf" quantity="134">69</measure>
69 leaves.

2023-12-05 13:40 UTC, CarstenHoffmannMarburg commented on FlorenceBML/BMLacq784/BMLacq784.xml
> +                                    <measure unit="quire" quantity="14">9</measure>
9 quires.

2023-12-05 13:45 UTC, thea-m approved these changes

2023-12-05 13:45 UTC, merged