Update BMLacq821
BetaMasaheft/Manuscripts pull request #2224
Opened 2023-12-13 11:19 UTC by CarstenHoffmannMarburg

I updated the record for BMLacq821. To my surprise, the transcription by transcribus was inserted in the ms-file. It may be necessary to split this record into two to have the transcribus record seperately.

2023-12-13 18:25 UTC, CarstenHoffmannMarburg commented
I wanted to encode Josef in ms_i6, but I did not find an ID for him. It is supposed to be Joseph, the son of Jacob and Rachel, who is registered as Q145746 in Wikiquote. Is his record missing in Bm?

I checked EMIP00227 and LIT6751PPAynat and discovered some similarities to ms_i6 in the manuscript and in the record respectively. However, I saw, that the link [www.betamasaheft.eu/LIT6751PPAynat](https://betamasaheft.eu/works/LIT6751PPAynat/main) is not available at the moment.

2023-12-14 08:25 UTC, thea-m commented
It's PRS5763Joseph. I've added the wikidata ID and the Bm ID to wikidata.

2023-12-14 08:36 UTC, eu-genia requested changes

2023-12-14 08:36 UTC, eu-genia commented on FlorenceBML/BMLacq821/BMLacq821.xml
> +                			<ab type="script"/>
why this `ab`?

2023-12-14 08:38 UTC, eu-genia commented
No, it is not necessary to split the record at all.
We split only when the transcriptions are too long for github.
If you see an error on calling an entry (as in LIT6751PPAynat) it is not because the "link is unavailable" but because there is an encoding issue or a problem with the code, and an issue is needed to settle the bug (done).

2023-12-14 10:54 UTC, CarstenHoffmannMarburg commented on FlorenceBML/BMLacq821/BMLacq821.xml
> +                			<ab type="script"/>
Deleted `<ab type="script"/>`

2024-02-07 10:53 UTC, eu-genia approved these changes

2024-02-07 10:53 UTC, merged