EYQG 001 - 006
BetaMasaheft/Manuscripts pull request #2244
Opened 2024-01-25 13:21 UTC by DenisNosnitsin1970

The first six mss from Enda Yohannes.

2024-01-25 13:28 UTC, eu-genia requested changes

2024-01-25 13:28 UTC, eu-genia commented on Enda Yohannes Qolla Gable/EYQG001.xml
> +                             The manuscript was commisioned by wayzaro Zanabaš Walda Giyorgis and donated by her to
commissioned (ss)

2024-01-25 13:28 UTC, eu-genia commented on Enda Yohannes Qolla Gable/EYQG001.xml
> +                             The manuscript was commisioned by wayzaro Zanabaš Walda Giyorgis and donated by her to
Zanabaš or Zannabaš ?

2024-01-25 13:28 UTC, eu-genia commented on Enda Yohannes Qolla Gable/EYQG002.xml
> +                             The manuscript was an individual and donated by him to <placeName ref="INS1008EndaYohannes">ʾƎndā Yoḥannǝs Māy Kʷāḵʷ</placeName>.
had been **owned by** an individual?

2024-01-25 13:31 UTC, DenisNosnitsin1970 commented on Enda Yohannes Qolla Gable/EYQG001.xml
> +                             The manuscript was commisioned by wayzaro Zanabaš Walda Giyorgis and donated by her to
ok

2024-01-25 13:31 UTC, DenisNosnitsin1970 commented on Enda Yohannes Qolla Gable/EYQG002.xml
> +                             The manuscript was an individual and donated by him to <placeName ref="INS1008EndaYohannes">ʾƎndā Yoḥannǝs Māy Kʷāḵʷ</placeName>.
corrected

2024-01-25 13:34 UTC, eu-genia commented
@line-o sorry can you check why the test has failed? I cannot see the error reported, and in Oxygen all is green. thanks!

2024-01-25 15:41 UTC, thea-m requested changes
Nice :)

2024-01-25 15:41 UTC, thea-m commented on Enda Yohannes Qolla Gable/EYQG001.xml
> +                    <term key="Rituals"/>
Hagiography?

2024-01-25 15:41 UTC, thea-m commented on Enda Yohannes Qolla Gable/EYQG002.xml
> +                             The name other persons,  Walatta  ʿAbiya ʾƎgziʾ, Gabra Yoḥannǝs are mentioned in the supplication formulas.
names of

2024-01-25 15:41 UTC, thea-m commented on Enda Yohannes Qolla Gable/EYQG003.xml
> +                             The hand is similar to that of .
reference missing?

2024-01-26 10:29 UTC, DenisNosnitsin1970 commented on Enda Yohannes Qolla Gable/EYQG001.xml
> +                    <term key="Rituals"/>
ok

2024-01-26 10:29 UTC, DenisNosnitsin1970 commented on Enda Yohannes Qolla Gable/EYQG002.xml
> +                             The name other persons,  Walatta  ʿAbiya ʾƎgziʾ, Gabra Yoḥannǝs are mentioned in the supplication formulas.
ok

2024-01-26 10:34 UTC, DenisNosnitsin1970 commented on Enda Yohannes Qolla Gable/EYQG003.xml
> +                             The hand is similar to that of .
yes, sorry.

2024-01-26 11:56 UTC, eu-genia commented
Now I know what is wrong. Your folder name has spaces in it.
You may never ever ever have file names or folder names with spaces.

2024-01-26 12:25 UTC, merged