Enda Yohannes further mss
BetaMasaheft/Manuscripts pull request #2250
Opened 2024-01-29 13:54 UTC by DenisNosnitsin1970

Enda Yohannes 14 - 20

2024-01-29 14:00 UTC, eu-genia approved these changes

2024-01-29 14:14 UTC, thea-m requested changes

2024-01-29 14:14 UTC, thea-m commented on EndaYohannesQollaGable/EYQG014.xml
> +                                   on the hourse back, with a boy behind.</desc>
on horseback

2024-01-29 14:14 UTC, thea-m commented on EndaYohannesQollaGable/EYQG014.xml
> +                               <desc><ref type="authFile" corresp="AT1031VirginAndChild"/> (mirrored?) and two Engels.</desc>
angels

2024-01-29 14:14 UTC, thea-m commented on EndaYohannesQollaGable/EYQG015.xml
> +                               ዝተጽሕፈ፡ በ<date>፲፱፻፶፪ዓመተ፡ ምሕረት፡</date> በወንጀላዊ፡ <hi rend="rub">ዮሐንስ፡</hi> ወዘመነ፡ <persName ref="PRS5226haylase">ንጉሥነ፡ <hi rend="rub">ኃይለ፡ ሥላሴ፡</hi>
hi rend="rubric" throughout

2024-01-29 14:14 UTC, thea-m commented on EndaYohannesQollaGable/EYQG017.xml
> +                                   ʾAmāraš Gabra Mikāel, copied in or shortly before 1962 EC (1969/70 CE).
Mikāʾel

2024-01-30 10:51 UTC, DenisNosnitsin1970 commented on EndaYohannesQollaGable/EYQG014.xml
> +                                   on the hourse back, with a boy behind.</desc>
ok

2024-01-30 10:51 UTC, DenisNosnitsin1970 commented on EndaYohannesQollaGable/EYQG014.xml
> +                               <desc><ref type="authFile" corresp="AT1031VirginAndChild"/> (mirrored?) and two Engels.</desc>
ok

2024-01-30 10:51 UTC, DenisNosnitsin1970 commented on EndaYohannesQollaGable/EYQG015.xml
> +                               ዝተጽሕፈ፡ በ<date>፲፱፻፶፪ዓመተ፡ ምሕረት፡</date> በወንጀላዊ፡ <hi rend="rub">ዮሐንስ፡</hi> ወዘመነ፡ <persName ref="PRS5226haylase">ንጉሥነ፡ <hi rend="rub">ኃይለ፡ ሥላሴ፡</hi>
indeed

2024-01-30 10:51 UTC, DenisNosnitsin1970 commented on EndaYohannesQollaGable/EYQG017.xml
> +                                   ʾAmāraš Gabra Mikāel, copied in or shortly before 1962 EC (1969/70 CE).
ok

2024-01-30 11:36 UTC, merged