BDLaethf28
BetaMasaheft/Manuscripts pull request #2266
Opened 2024-02-02 18:07 UTC by thea-m

Hey everyone, this is the last manuscript from me. See also https://github.com/BetaMasaheft/Works/pull/690
The description is very minimal. A more detailed description of the content would be desirable, but would take up considerable resources. If you think that this is not up to our catalogue's standards, we will reconsider and see what can be done.

2024-02-05 17:26 UTC, MassimoVilla requested changes
Dear Dorothea, thank you.
The text has no internal subdivision, so it is difficult to produce a more detailed description of the content without going through the entire text page after page, which would be much time-consuming and - I think - would exceed the purpose of our catalogue. So, I think we can stick to the current description.
I am uncertain about  the transcription of some poorly readable portions in Amharic. Perhaps they should be revised by a native speaker. Has Solomon already seen them when he prepared the first draft of the description?

2024-02-06 17:01 UTC, gnizla approved these changes

2024-02-06 18:03 UTC, ElianaDalSasso approved these changes
Thank you Thea! In my opinion the description of the manuscript is fine for the catalogue, even if it is not detailed as the others. The introductory note is informative.
I have just a question, ca we give the information contained in JJ handout? I think it is interesting.

2024-03-19 11:18 UTC, thea-m commented
Can this be merged @karljonaskarlsson ?

2024-03-20 14:09 UTC, karljonaskarlsson requested changes

2024-03-20 14:09 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethf28.xml
> +                                    <desc type="findingAid">‘Nr. 19’ written in Amharic in the upper margin.</desc>
Is "Nr." a normal translation of the Amharic? If so, I think we should use "No." instead for "number". Here and some lines below.

2024-03-20 14:09 UTC, karljonaskarlsson commented on OxfordBodleian/Juel-Jensen/BDLaethf28.xml
> +                                <date notBefore="1800" notAfter="1998"/>
If we do not use the information from the handout, does it make sense to say "1998"? Maybe rather an even number?

2024-03-22 09:40 UTC, merged