Create BLorient8817
BetaMasaheft/Manuscripts pull request #2280
Opened 2024-02-13 18:10 UTC by CarstenHoffmannMarburg

I created a record for BLorient8817. 

The ID for the malkǝʾ was discussed in https://github.com/BetaMasaheft/Documentation/issues/2485.

2024-02-13 18:20 UTC, eu-genia requested changes

2024-02-13 18:20 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient8817.xml
> +                                    <q>Bequeathed by <persName ref="PRS14320DareaCurzon">Darea Baroness Zouche</persName>.
role="bequeather"

2024-02-13 18:20 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient8817.xml
> +                            <persName ref="PRS14333QatsalaGiyorgis">Qäṣälä Giyorgis</persName>.
Qaṣala

2024-02-13 18:20 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient8817.xml
> +                            the name of the first owner was <persName ref="PRS14334HabtaMaryam">Habta Māryām</persName> of the second
role="owner" etc

2024-02-14 10:15 UTC, eu-genia approved these changes

2024-02-14 11:09 UTC, thea-m approved these changes

2024-02-14 11:09 UTC, merged