Create BLorient13264
BetaMasaheft/Manuscripts pull request #2283
Opened 2024-02-14 15:04 UTC by CarstenHoffmannMarburg

I created a record for BLorient13264. I could not identify the prayer in ms_i7. I checked Leanders edition of the Prayers of Simeon Stylites and the unidentified prayer is not part of this edition.

I made a minor change also in BAVet57, because I have discovered, that the prayer of Ephraim encoded there is to be identified with LIT4239Prayer as well.

2024-02-14 15:40 UTC, eu-genia requested changes

2024-02-14 15:40 UTC, eu-genia commented on VaticanBAV/et/BAVet57.xml
>                                ማርያም፡ ወላዲተ፡ አምላክ፡ ጸግወነ፡ እግዚኦ፡ ስርየተ፡ ኃጣውኢነ፡ ንሰግድ፡ ለከ፡ ኦክርስቶስ፡ ምስለ፡ አቡከ፡ ኄር፡ ወመንፈስ፡ ቅዱስ፡</q>), a prayer entitled
Thank you! Ideally, this list should be transformed in 
a list of `<msItem xml:id="ms_i1.2.1">` etc, each with its own `title `and where provided `incipit` but I agree this is a lot of work, so thank you for inserting the reference so it is not lost

2024-02-14 15:40 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient13264.xml
> +                                <foliation>Seventeen ouf of eighteen quires are numbered with quiremarks.</foliation>
quire numbering is not part of `foliation `but of `collation`

according to the TEI guidelines the best element could be `signatures `https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-signatures.html (inside `collation`)

2024-02-14 15:40 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient13264.xml
> +                            <citedRange unit="page">9-10</citedRange></bibl> taken from King Theodore's Library in Magdala in
mark down  `<persName ref="PRS9430Tewodros"/>` and `<placeName ref="INS0101MadhaneAlam"/>`

2024-04-04 10:19 UTC, thea-m requested changes
Thank you!

2024-04-04 10:19 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13264.xml
> +                                <supplied reason="omitted" resp="Strelcyn">ይትባረክ፡ ስሙ፡</supplied> ወይትለዓል፡ ዝክሩ፡ ወፍጽምናሁ፡ ዘእምኔሁ፡ ሢመተ፡ ኵሉ፡
I think the PRS ID has to be used in resp

2024-04-04 10:19 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13264.xml
> +                                    <measure unit="leaf" type="blank" corresp="#2v #66v #81v #142v #150">5</measure>
page

2024-04-04 10:19 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13264.xml
> +                                    <q xml:lang="en">ሰላም፡ ሰላም፡ ለዝክር፡ ስምኪ፡ በአምሐ፡ </q>
gez

2024-04-04 10:19 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13264.xml
> +                                <decoNote xml:id="b3" type="Cover"><material key="leather">Stamped leather.</material></decoNote>
blind-tooled

2024-04-16 14:14 UTC, thea-m approved these changes

2024-04-16 14:14 UTC, merged