Update BAVet20.xml
BetaMasaheft/Manuscripts pull request #2285
Opened 2024-02-15 08:07 UTC by thea-m

2024-02-15 08:12 UTC, eu-genia approved these changes
great

2024-02-15 08:26 UTC, CarstenHoffmannMarburg commented on VaticanBAV/et/BAVet20.xml
> +                  <acquisition notAfter="1487">The manuscript was already part of the library’s collection by <date>1487</date>,
You mean the library in the Vatican and not in Jerusalem. Otherwise one might think, that Brocchi borrowed it from the Jerusalem monastic library.

2024-02-15 08:27 UTC, eu-genia requested changes

2024-02-15 08:27 UTC, eu-genia commented on VaticanBAV/et/BAVet20.xml
> +                     to <placeName ref="LOC3957Jerusa">Jerusalem</placeName> by <persName ref="PRS14337Baptista"/>
missed this one: please leave our old Brocchi here, thank you!

2024-02-15 08:28 UTC, eu-genia requested changes

2024-02-15 08:28 UTC, eu-genia commented on VaticanBAV/et/BAVet20.xml
> +                     this makes it the Biblioteca Apostolica Vaticana’a longest-held Ethiopic manuscript. </acquisition>
Vaticana's

2024-02-16 07:49 UTC, CarstenHoffmannMarburg approved these changes

2024-04-03 12:54 UTC, eu-genia approved these changes

2024-04-25 16:26 UTC, merged