Update Frankfurt mss. on Walda Amid
BetaMasaheft/Manuscripts pull request #2286
Opened 2024-02-15 15:51 UTC by CarstenHoffmannMarburg

I updated the records of FSUor134 and FSUor40. The principal change is, that I exchanged the general record LIT4723TarikaWaldaAmid for the more specific LIT6936TarWaAmidBeta in FSUor134 as it is necessary due to the latest reworking of the work records on the Tarika Walda Amid. 
However, I did some minor changes in both records as well, i.e. I deleted the note on the non-existence of Zarʾa Yāʿqob in the Translation note. This note can only be understood from the point of view of one single recension, as Goldschmidt assumed. Nowadays, it is clear, that there have been two translations and that the second translation was done in the time of Lebna Dengel. For that reason it is nothing extraordinary in this translation note in comparison to other witnesses of the beta recension. 
In FSUor40, I found nothing, that needs to be urgently changed. I just made a minor change on the alledged participation of the prominent Liq ʾAṣqu. The fact, that Liq ʾAṣqu  copied this codex by his own hand is reported in Rüppells Reisebericht, which is not always reliable, but to my knowledge Liq ʾAṣqus name does not occur in the manuscript. I try to find the specific place in a minute.

2024-02-15 16:05 UTC, CarstenHoffmannMarburg commented
I found a note concerning the hand of Liq ʾAṣqu in my dissertation (p. 82):
"Handschriftliche Notiz von Eduard Rüppell im Einband: „Kleine Chronik von Lik Atkum zu Gondar geschrieben“; siehe auch Kropp 2018, S. 263 u. 266-7 sowie 1989, S. 237; Rüppell 1840, S. 106 und 336-7. "
I therefore edited the comment above.

2024-02-15 22:32 UTC, eu-genia approved these changes

2024-02-16 07:47 UTC, thea-m requested changes
Wonderful, just please acknowledge your own work in a change element :)

2024-02-16 08:16 UTC, thea-m approved these changes

2024-02-16 08:16 UTC, merged