Abb 191 154
BetaMasaheft/Manuscripts pull request #2289
Opened 2024-02-20 16:44 UTC by DenisNosnitsin1970

One new record, corrects in two others.

2024-02-20 18:33 UTC, CarstenHoffmannMarburg commented on ParisBNF/abb/BNFabb191.xml
> +           <title>Commentaries in in Gǝʿǝz on the Gospel of Matthew, Luke, and John, </title>
delete one of the "in"

2024-02-20 18:33 UTC, CarstenHoffmannMarburg commented on ParisBNF/abb/BNFabb191.xml
> +                                  <foliation>Foliation in the upper right corner of the folia. The first two parchment leave are not foliated (assigned the numbers
leaves

2024-02-20 18:33 UTC, CarstenHoffmannMarburg commented on ParisBNF/abb/BNFabb191.xml
> +                                                    can be dated to 1647 CE (=1328 according to the Era of Alexander the Great).
'era' according to deepl write.

2024-02-20 18:53 UTC, eu-genia requested changes

2024-02-20 18:53 UTC, eu-genia commented on ParisBNF/abb/BNFabb191.xml
> +           <title>Commentaries in in Gǝʿǝz on the Gospel of Matthew, Luke, and John, </title>
and comma in the end

2024-02-20 18:53 UTC, eu-genia commented on ParisBNF/abb/BNFabb191.xml
> +                                  <condition key="good">The original binding is missing; all quires are dismantled,
good?

2024-02-20 18:53 UTC, eu-genia commented on ParisBNF/abb/BNFabb191.xml
> +                                                  According to <ref target="#colop1"/>, at least part of the manuscript
`<ref target="#coloph1">colophon 1</ref>`

2024-02-21 10:28 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb191.xml
> +           <title>Commentaries in in Gǝʿǝz on the Gospel of Matthew, Luke, and John, </title>
ok

2024-02-21 10:33 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb191.xml
> +                                  <foliation>Foliation in the upper right corner of the folia. The first two parchment leave are not foliated (assigned the numbers
ok

2024-02-21 10:34 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb191.xml
> +                                                    can be dated to 1647 CE (=1328 according to the Era of Alexander the Great).
In the Bm predominantly "Era".

2024-02-21 10:34 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb191.xml
> +                                  <condition key="good">The original binding is missing; all quires are dismantled,
ok, changed.

2024-02-21 10:36 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb191.xml
> +                                                  According to <ref target="#colop1"/>, at least part of the manuscript
ok

2024-02-21 11:05 UTC, eu-genia approved these changes

2024-02-21 11:19 UTC, merged