Create BLorient4611
BetaMasaheft/Manuscripts pull request #2306
Opened 2024-03-05 11:48 UTC by CarstenHoffmannMarburg

I created a record for BLorient4611 based on Strelcyns catalogue. I did not know, if I should create a LIT ID for a2 (magical prayer against enemies) and started an issue (https://github.com/BetaMasaheft/Documentation/issues/2496) just a couple of minutes ago.

2024-03-06 08:43 UTC, eu-genia requested changes

2024-03-06 08:43 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient4611.xml
> +                                        <note>Indicated by the title: <q xml:lang="gez">ጸሎተ፡ ሐና፡ እመ፡ ሳሙኤል፡ ነቢይ፡</q></note>
possibly better `<incipit xml:lang="gez"><title>ጸሎተ፡ ሐና፡ እመ፡ ሳሙኤል፡ ነቢይ፡</title></incipit>`
https://betamasaheft.eu/Guidelines/?q=title&id=ColophSupplTit

2024-03-06 08:43 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient4611.xml
> +                                <note>With musical notation. Arranged by the days of the week, with Monday's lesson first.</note>
`<notatedMusic><desc>With musical notation</desc></notatedMusic>`
`<note>Arranged by the days of the week, with Monday's lesson first.</note>`

2024-03-06 08:43 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient4611.xml
> +                                    <q xml:lang="en">Bought of Mr. <persName ref="PRS14356Brion">F. Brion</persName>
owner

2024-03-06 08:43 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient4611.xml
> +                            <binding xml:id="binding">
`<binding contemporary="false">`

2024-03-07 19:34 UTC, eu-genia requested changes

2024-03-07 19:34 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient4611.xml
> -                                <title ref="LIT2000Mazmur"/>
this should stay though

2024-03-07 19:34 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient4611.xml
> -                                        <title ref="LIT2257salota"/>
also here, etc. put all titles back and reread the guidelines link i had provided, thank you

2024-03-07 19:34 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient4611.xml
> -                                <title ref="LIT2000Mazmur"/>
markup of the `incipit `is not the same as `msItem`, these are two different things, `msItem `needs a `title`, `incipit `may have a `type `or an inner markup

2024-03-11 16:39 UTC, thea-m approved these changes

2024-03-14 13:22 UTC, eu-genia approved these changes

2024-03-14 14:34 UTC, merged