Create BLorient12114A
BetaMasaheft/Manuscripts pull request #2310
Opened 2024-03-11 08:41 UTC by CarstenHoffmannMarburg

I created a record according to the description in S. Strelcyns catalogue.

2024-03-11 13:38 UTC, DenisNosnitsin1970 requested changes

2024-03-11 13:38 UTC, DenisNosnitsin1970 commented on LondonBritishLibrary/orient/BLorient12114A.xml
> +                                <decoNote xml:id="b2" type="Boards"><material key="wood"/>Wooden boards.</decoNote>
"The binding is badly damaged" would be better under "Condition"

2024-03-11 13:38 UTC, DenisNosnitsin1970 commented on LondonBritishLibrary/orient/BLorient12114A.xml
> +                                    <q xml:lang="gez"><title ref="LIT2000Mazmur">መዝሙር፡ ዘዳዊት።</title></q></note>
I think he does not mean "chapters"; he means the so-called traditional title of each psalm which exist in several versions. Here, each of them has the title Mazmur za-dawit.

2024-03-11 13:38 UTC, DenisNosnitsin1970 commented on LondonBritishLibrary/orient/BLorient12114A.xml
> +                                <date notBefore="1600" notAfter="1800" resp="PRS8999Strelcyn"/>
Do we have any guidelines as to how we write the dating? Strelcyn might probably mean "17th or 18th century" (what I  personally indicate 17th/18th century). The dating embracing the span of 200 years is a little odd (in his catalogue mostly without arguments anyway).

2024-03-11 13:55 UTC, eu-genia requested changes

2024-03-11 13:55 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient12114A.xml
> +                                <collation>One bifolium after <ref target="#141"/>, one leaf after <ref target="#150"/>, probably two leaves after
I think this belongs to condition. Collation is about the composition of the quires.

2024-03-11 13:55 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient12114A.xml
> +                                <title ref="LIT1233Cantic"/>
`type="incomplete"`

2024-03-11 13:55 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient12114A.xml
> +<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="BLorient12114" xml:lang="en" type="mss">
`xml:id` must be the same as the name of the file

2024-03-14 13:24 UTC, eu-genia approved these changes

2024-05-21 07:04 UTC, CarstenHoffmannMarburg commented
@DenisNosnitsin1970 
I think, I made the changes, that you requested. Can this branch be merged?

2024-06-01 00:41 UTC, merged