Create BLorient13269
BetaMasaheft/Manuscripts pull request #2339
Opened 2024-03-28 17:57 UTC by CarstenHoffmannMarburg

I created this record according to S. Strelcyns catalogue. 

I was not quite sure whether LIT6563HassabHeg was the correct ID for Ḥasāba ḥǝgg (movable feast calendar) in ms_i1. I think it is the ID for all calendar calculations for movable festivals, no matter if these calculations start and end in different years and use different cycles. 

I was even less sure about ms_i2. Strelcyn refers to it simply as "Kidan", as was the case in BLorient8813. But here there is no incipit or other information, so I can only speculate whether it is LIT2260salota again, or LIT1938Mashaf, or some other work with that name. I think it would be better to leave it unmarked.

2024-03-29 16:34 UTC, DenisNosnitsin1970 commented
The Hassabe heg with 6563 appears to be different, as to Kidan, please check LIT3058RepCh338.

2024-03-30 05:18 UTC, CarstenHoffmannMarburg commented
> The Hassabe heg with 6563 appears to be different,

The incipit in BLorient13269 seems to be more close to the one attested in IVorlov34, that does not have a markup, yet:

```
<item xml:id="a2">
                           <desc type="Unclear" xml:lang="gez"/>
                          <locus from="2v" to="3v"/>
                          <q xml:lang="gez"> በዝ᎓ ንዜከር᎓  ሐሳበ᎓ ሕጉ᎓ ለእግዚእነ᎓ ወመድኃኒነ᎓ ኢ᎓ ክ᎓
                            <gap reason="omitted" resp="PRS9602Turaev"/>እንዘ᎓ ሀሎነ᎓ በዘበነ᎓ ቅዱስ᎓ ማርቆስ᎓
                            ወንገላዊ᎓ ይብጽሐነ᎓ እስከ᎓ ዘበነ᎓ ሉቃስ᎓ ዜናዊ። በ፶፲ት᎓ በ፭ቱ፻ት᎓ ኮነ᎓ ዓመተ᎓ ዓለም። በ፲ቱ᎓ ፻።
                            በ፲ቱ᎓ ፻፺᎓ ኮነ᎓ ዓመተ᎓ ምሕረት᎓<gap reason="omitted" resp="PRS9602Turaev"/>
                           </q>
                           <note>Chronological notes written on a sewn-in European paper leaf.</note>
                       </item>
```
Do you think, it is appropriate to create a new ID in this case?

2024-03-30 05:26 UTC, CarstenHoffmannMarburg commented
> as to Kidan, please check LIT3058RepCh338.

I have used LIT3058RepCh338 for ms_i3 as it is evident from the incipit.

However, for ms_i2, I have no information beyond the title kidān.

<img width="648" alt="Screenshot 2024_Kidan" src="https://github.com/BetaMasaheft/Manuscripts/assets/40291787/e2fe4ac6-86b9-4c66-b973-d6b7ea164fb4">

2024-03-30 08:32 UTC, DenisNosnitsin1970 commented
Yes, it is upropriate to make a new record for Hassaba heg, you can use relations to disambiguate it from  LIT6563HassabHeg. Please lead a discussion in "Issues", here we only correct / comment upon descriptions, for better transparency.

2024-04-18 20:11 UTC, eu-genia requested changes

2024-04-18 20:11 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient13269.xml
> +                </keywords>
Chronography
Poetry
Liturgy

2024-04-18 20:11 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient13269.xml
> +                                    <desc type="GuestText">Traces of the beginning of a <foreign xml:lang="gez">salām</foreign> to the Archangel
we also have PoemSalam as a type for additions

2024-05-21 07:18 UTC, eu-genia approved these changes

2024-05-21 07:18 UTC, merged