Update BLorient13156 according to S. Strelcyn
BetaMasaheft/Manuscripts pull request #2347
Opened 2024-04-02 11:06 UTC by CarstenHoffmannMarburg

I updated the record according to the catalogue description in S. Strelcyn. For ms_i4 I recommend to create a new LIT ID as outlined in https://github.com/BetaMasaheft/Documentation/issues/2513.

2024-04-02 12:09 UTC, thea-m requested changes
Thank you, very nice!

2024-04-02 12:09 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13156.xml
> +                            <note>To be recited over the water in which a sick person is to bath and over the oil with which he is to be anointed for
bathe?

2024-04-02 12:09 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13156.xml
> +                            <note>To be recited over the water in which a sick person is to bath and over the oil with which he is to be anointed for
they are instead of he is?

2024-04-02 12:09 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13156.xml
> +                                <desc>Miniature depicting <ref type="authFile" corresp="AT1105HolyWoman">Our Lady</ref> at prayer while
AT1099StMary?

2024-04-02 12:09 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13156.xml
> +                                <item xml:id="e3">
It would be good to add `<q xml:lang="la">` (and possible a second one for Italian) to make this filterable

2024-04-02 12:09 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13156.xml
> +                            On <ref target="#119r"/> two other persons are named together with
locus

2024-04-02 12:09 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13156.xml
> +                                <desc>Symbolic signs referring to Christ on the margins on <ref target="#23v"/> and on various pages of the codex.</desc>
locus

2024-04-03 07:08 UTC, eu-genia approved these changes

2024-04-03 10:08 UTC, merged