BAVet145
BetaMasaheft/Manuscripts pull request #2374
Opened 2024-04-11 14:14 UTC by thea-m

2024-04-11 22:43 UTC, eu-genia requested changes

2024-04-11 22:43 UTC, eu-genia commented on VaticanBAV/et/BAVet120.xml
> +    <placeName ref="LOC3056Farta">ፋርጣ፡</placeName> ዓዲኮ፡ <placeName ref="INS1013FAG">ገብርኤል</placeName>፡
I would only markup `<placeName ref="INS1013FAG">ፋርጣ፡ ዓዲኮ፡ ገብርኤል</placeName>`, the information on warada and qabale is for the settlement section of the INS1013FAG record

2024-04-11 22:43 UTC, eu-genia commented on VaticanBAV/et/BAVet145.xml
> +                              <placeName ref="INS1013FAG">ገብር<lb/>ኤል፡</placeName> ዘወሀቦ፡
as above

2024-04-12 09:11 UTC, eu-genia approved these changes

2024-04-12 09:55 UTC, DenisNosnitsin1970 requested changes

2024-04-12 09:55 UTC, DenisNosnitsin1970 commented on VaticanBAV/et/BAVet145.xml
> +                            <q xml:lang="gez">ዝመጽሐፍ፡ <placeName ref="LOC1713Bagemd"><sic>ዘለጌምድር፡</sic></placeName>
this is definitely በ.

2024-04-12 09:55 UTC, DenisNosnitsin1970 commented on VaticanBAV/et/BAVet145.xml
> +                            <q xml:lang="am">፯ተኛው፡ ጥራዝ፡ <supplied reason="omitted">የ</supplied>ሚፈጽም፡ ደዳቤውን፡ ፈልጎ፡</q>
please add ብ after ደ

2024-04-12 09:55 UTC, DenisNosnitsin1970 commented on VaticanBAV/et/BAVet145.xml
> +                            <q xml:lang="gez">ዝመጽሐፍ፡ <placeName ref="LOC1713Bagemd"><sic>ዘለጌምድር፡</sic></placeName>
The sense of the note is escaping me :)

2024-04-15 07:05 UTC, CarstenHoffmannMarburg approved these changes

2024-04-17 13:54 UTC, merged