Create BLorient13278
BetaMasaheft/Manuscripts pull request #2385
Opened 2024-04-19 10:55 UTC by CarstenHoffmannMarburg

I created a record according to S. Strelcyns description. I was able to identify the msItems, except for ms_i2, for which I propose a new LIT ID, as I have outlined in https://github.com/BetaMasaheft/Documentation/issues/2520.

Unfortunately, I made a mistake and created a record called BL13278 instead of BLorient13278 as it should be. I have created another new record with the correct name. The outdated earlier issue can be ignored in this pull request, but should be deleted in a new pull request immediately after merging this one. If I remember correctly, a new pull request is needed, otherwise the deletion will cause chaos in the application. Is this correct?

2024-04-24 07:27 UTC, thea-m requested changes
Nice, thank you!

2024-04-24 07:27 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13278.xml
> +            <titleStmt>
ya-

2024-04-24 07:27 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13278.xml
> +                            <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> በዚህቺ፡ በቅድስት፡ ሥላሴ፡ ሠራነ፡ መስሪነታቺው፡ ፩አምላክ፡ በሚባል፡ አንደነታቺው፡ አብ፡
am

2024-04-24 07:27 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13278.xml
> +                        <msItem xml:id="ms_i1">
the element textLang can be added to every msItem

2024-04-24 07:27 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient13278.xml
> +                            <title>Three miracles of the Virgin Mary</title>
LIT3585Taamme

2024-04-25 13:35 UTC, thea-m commented
My understanding here would be that the wrongly created record can be in this case deleted before the branch is merged

2024-04-26 07:08 UTC, eu-genia commented
If a record was created in Oxygen only (without the app) it can be always renamed/deleted/moved at any time, without waiting to merge first. This is actually recommended to limit the traffic to the server.

ONLY records created through the app MUST be synced first.

2024-04-26 07:16 UTC, eu-genia requested changes

2024-04-26 07:16 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient13278.xml
> +<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="BLorient13278" xml:lang="en" type="mss">
if you created the first version directly in Oxygen there was no need to create a copy, you could simply rename the file and update the `xml:id`

if you created the first version in the APP then it must be first saved in the `new `folder and then synced first

2024-04-26 07:16 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient13278.xml
> +                                <desc><ref type="authFile" corresp="AT1041HolyMen">Miniature of
NB every `corresp `= hyperlink
Now you have one hyperlink (`persName`) inside of another (`ref`), the computer cannot process this.
Please do not overlap.
either close the `ref `immediately `<ref type="authFile" corresp="AT1041HolyMen"/> `  or at least before `persName `starts

2024-04-26 07:16 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient13278.xml
> +                                <desc><ref type="authFile" corresp="AT1082Angel">Miniature of the
as above

2024-04-26 07:16 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient13278.xml
> +                                <desc>Empty space intended for a <ref type="authFile" corresp="AT1082Angel">miniature of the
as above

2024-04-26 07:16 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient13278.xml
> +                <language ident="gez">Gǝʿǝz</language>
`am`

2024-04-26 09:51 UTC, thea-m approved these changes

2024-07-05 12:13 UTC, eu-genia approved these changes

2024-07-08 12:18 UTC, merged