Create BNFabb213.xml
BetaMasaheft/Manuscripts pull request #2461
Opened 2024-06-17 10:06 UTC by DenisNosnitsin1970

Another d'Abbadie ms.

2024-06-17 18:49 UTC, CarstenHoffmannMarburg requested changes

2024-06-17 18:49 UTC, CarstenHoffmannMarburg commented on ParisBNF/abb/BNFabb213.xml
> +                    (according to C. Conti Rossini, at <placeName ref="INS0303BNF">Beta Lǝḥem</placeName>, in 1845).
The date 1845 in line 98 is redundant.

2024-06-18 19:18 UTC, DenisNosnitsin1970 commented on ParisBNF/abb/BNFabb213.xml
> +                    (according to C. Conti Rossini, at <placeName ref="INS0303BNF">Beta Lǝḥem</placeName>, in 1845).
ok

2024-06-19 08:35 UTC, CarstenHoffmannMarburg approved these changes

2024-06-19 08:48 UTC, merged