Create BLorient11764.xml
BetaMasaheft/Manuscripts pull request #2587
Opened 2024-09-03 16:20 UTC by CarstenHoffmannMarburg

New LIT IDs for ms_i3, ms_i4, ms_i5 and ms_i6 have been created after discussion in https://github.com/BetaMasaheft/Documentation/issues/2594, https://github.com/BetaMasaheft/Documentation/issues/2596, https://github.com/BetaMasaheft/Documentation/issues/2597 and https://github.com/BetaMasaheft/Documentation/issues/2598.

It would be nice to have an art theme for magic pictures, but I assume, that there is none. So I marked them up simply as "miniatures".

2024-09-05 12:14 UTC, karljonaskarlsson approved these changes

2024-09-05 12:22 UTC, eu-genia commented
Most "magic pictures" I know are schematic drawings, not miniatures.

2024-09-05 12:24 UTC, eu-genia requested changes

2024-09-05 12:24 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient11764.xml
> +            <langUsage><language ident="en">English</language><language ident="gez">Gǝʿǝz</language></langUsage>
keywords

2024-09-05 12:24 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient11764.xml
> +                            <decoNote xml:id="d1" type="miniature">
drawing

2024-09-05 12:24 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient11764.xml
> +                                <desc>Coloured magic picture.</desc>
you can mark up magic as a term, then one could search for all drawings containing the keyword in our filtered search

2024-09-09 15:34 UTC, nafisa-valieva approved these changes

2024-09-19 11:35 UTC, eu-genia approved these changes

2024-09-19 12:00 UTC, merged