Dr 23 06 corrections
BetaMasaheft/Manuscripts pull request #2620
Opened 2024-09-18 15:02 UTC by thea-m

2024-09-18 16:30 UTC, eu-genia commented
You can comment out the included facsimile in the main record but not in the facsimile.xml, this file remains as is.
If you comment the xiinclude out, it will not be expanded anyway.
you cannot comment a root element out, it will clearly rend any xml file invalid, xml files must have root elements

2024-09-18 16:32 UTC, eu-genia requested changes

2024-09-19 14:06 UTC, thea-m commented
Great, thank you!

2024-09-19 14:28 UTC, eu-genia approved these changes
thank you
I just reinstated the facsimile.xml to the previous state to have fewer changes in the merge and in the revision history

2024-09-19 14:28 UTC, merged