Bavet121 desc
BetaMasaheft/Manuscripts pull request #2678
Opened 2024-11-05 10:25 UTC by MassimoVilla

Here comes BAVet121, a Dǝrsāna Mikāʾel followed by texts containing magic names

2024-11-06 08:29 UTC, CarstenHoffmannMarburg commented on VaticanBAV/et/BAVet121.xml
> +                                <seg type="script">19th-century script</seg>
19th century script

2024-11-06 10:59 UTC, eu-genia commented on VaticanBAV/et/BAVet121.xml
> +                                <seg type="script">19th-century script</seg>
why? it is correct with the dash

2024-11-06 11:03 UTC, eu-genia requested changes
thank you, wonderful!

2024-11-06 11:03 UTC, eu-genia commented on VaticanBAV/et/BAVet121.xml
> +                                    <note>The name of the owner <persName role="scribe" ref="PRS14580GabraMa ">Gabra Māryām</persName> is mentioned in the supplication formula at the end
remove space before the closing` "`

2024-11-06 11:03 UTC, eu-genia commented on VaticanBAV/et/BAVet121.xml
> +                                        The note is a short rhymed supplication written down by the scribe of the main text, <persName role="scribe" ref="PRS14580GabraMa ">Gabra Māryām</persName>.
remove space before "

2024-11-06 11:03 UTC, eu-genia commented on VaticanBAV/et/BAVet121.xml
> +        <t:profileDesc xmlns:t="http://www.tei-c.org/ns/1.0">
remove t: and xmlns

2024-11-06 11:03 UTC, eu-genia commented on VaticanBAV/et/BAVet121.xml
> +            <t:abstract>
remove t: throughout

2024-11-06 17:05 UTC, CarstenHoffmannMarburg approved these changes

2024-11-07 11:33 UTC, karljonaskarlsson requested changes

2024-11-07 11:33 UTC, karljonaskarlsson commented on VaticanBAV/et/BAVet121.xml
> +                                        ያድኅኖ፤ አመሣግሪሁ፡ ለሰይጣን፨ ለፍቅሩ፡ ወለጸሐፊሁኒ። ኃጥእ፡ ወአባሲ፡ ገብረ፡ ማርያም፡ ለዓ<supplied reason="omitted">ለ</supplied>መ፡ ዓለም፡ አሜን።
ለፍቁሩ፡ ?

2024-11-07 11:33 UTC, karljonaskarlsson commented on VaticanBAV/et/BAVet121.xml
> +                                  መላእክር፡ ሚካኤል<supplied reason="omitted">ል</supplied> እስከ፤ ዕለተ፡ ሞቱ፡ ትንብልናሁ፤
መላእክት፡ ?

2024-11-07 11:33 UTC, karljonaskarlsson commented on VaticanBAV/et/BAVet121.xml
> +                                አንሥአ፡ ኃ<supplied reason="omitted">ይ</supplied>ለከ፡ ወነዓ፡ አድኅነነ። ሚካኤል፡ ርድአነ፨ በጸሎትከ፡ ተማኅፀነ፨ አርዌ፡ ጊጉይ፡
አንሥእ

2024-11-07 11:33 UTC, karljonaskarlsson commented on VaticanBAV/et/BAVet121.xml
> +                                እሉ፡ ኩብራት፡ ወኅቡዓት፨ አስማቲ<supplied reason="omitted">ሁ፡</supplied> ለእግዚእነ፡ ዘተረክቡ፤ በእደ፡ ቅዱስ፡ ሊቀ፡ መላእክት፡ ሚካኤል፡ መግረሬ፡
ኩቡራት

2024-11-07 11:33 UTC, karljonaskarlsson commented on VaticanBAV/et/BAVet121.xml
> +                                        ለፍቅሩ፡ <space reason="owner" extent="unknown"/> ወዓዲ፡ ለጸሐፊሁ፡ ለዝንቱ፡ መጽሐፍ፡ ኃጥእ፡ ወአባሲ፡ ገብረ፡ ማርያም፡ በእንተ፡ ቅዱስ፡ ሚካኤል፡
`<space reason="owner" extent="unknown"/>` – this encoding inspires me! Thanks!

2024-11-07 11:33 UTC, karljonaskarlsson commented on VaticanBAV/et/BAVet121.xml
> +                                        መልአከ፡ ቅዳሴ። በረከቱ፡ ይኅድር፡ ላዕሌነ፨ በከመ፡ ኀደረ' በረከተ፤ ያዕቆብ፤ ላዕለ፡ ኤፍሬም፡ ወምናሴ፡ ለዓለመ፤ ዓለም፡ አሜን፨
" ኀደረ' ", is this as it should be?

2024-11-07 11:51 UTC, MassimoVilla commented on VaticanBAV/et/BAVet121.xml
> +                           <locus from="5r" to="4v"/>
Completely right, thank you

2024-11-07 11:57 UTC, MassimoVilla commented on VaticanBAV/et/BAVet121.xml
> +                                        መልአከ፡ ቅዳሴ። በረከቱ፡ ይኅድር፡ ላዕሌነ፨ በከመ፡ ኀደረ' በረከተ፤ ያዕቆብ፤ ላዕለ፡ ኤፍሬም፡ ወምናሴ፡ ለዓለመ፤ ዓለም፡ አሜን፨
ኀደረ፤ thank you!

2024-11-07 12:34 UTC, nafisa-valieva approved these changes

2024-11-07 16:22 UTC, karljonaskarlsson approved these changes

2024-11-07 22:12 UTC, eu-genia approved these changes

2024-11-08 07:24 UTC, merged