Emml1844 corr mk 8.11.24
BetaMasaheft/Manuscripts pull request #2706
Opened 2024-11-14 22:07 UTC by MarcinKrawczuk

https://github.com/BetaMasaheft/Documentation/issues/2682

2024-11-15 09:39 UTC, CarstenHoffmannMarburg requested changes

2024-11-15 09:39 UTC, CarstenHoffmannMarburg commented on EMML/1001-2000/EMML1844.xml
> +                  <idno>MS EMML no. 1840</idno>
It requires explanation, why the indo is EMML 1840, while the title of the record is EMML 1844.

2024-11-15 09:53 UTC, MarcinKrawczuk commented
It was a typo, sorry :(

pt., 15 lis 2024 o 10:40 Carsten Hoffmann ***@***.***>
napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In EMML/1001-2000/EMML1844.xml
> <https://github.com/BetaMasaheft/Manuscripts/pull/2706#discussion_r1843483369>
> :
>
> > @@ -31,41 +31,252 @@ schematypens="http://relaxng.org/ns/structure/1.0"?><?xml-model href="https://ra
>           <sourceDesc>
>              <msDesc xml:id="ms">
>                 <msIdentifier>
> -                  <repository ref="INS0004HMML"/>
> -                  <collection>Monastery of Ḥayq Esṭifānos, Ambāssal</collection>
> -                  <idno>MS EMML no. 1844</idno>
> +                  <repository ref="INS0327DHE"/>
> +                  <collection>Ethiopian Manuscript Microfilm Library</collection>
> +                  <idno>MS EMML no. 1840</idno>
>
> It requires explanation, why the indo is EMML 1840, while the title of the
> record is EMML 1844.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Manuscripts/pull/2706#pullrequestreview-2438127242>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJUFZQHGHZJSZH2BPBL2AW6QDAVCNFSM6AAAAABRZ4WGRWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMZYGEZDOMRUGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-17 22:38 UTC, eu-genia approved these changes

2024-11-18 09:19 UTC, CarstenHoffmannMarburg approved these changes

2024-11-18 10:26 UTC, merged