Maṣḥafa falāsfā ṭabibān recensions
BetaMasaheft/Manuscripts pull request #2707
Opened 2024-11-15 11:37 UTC by MassimoVilla

I have specified the IDs of the recension of the _Maṣḥafa falāsfā ṭabibān_ to which the msItems so far attributed to the general record LIT1925Mashaf belong.
Some msItems could not be identified due to missing incipits (e.g. DHAS007), so they still have LIT1925Mashaf

2024-11-15 11:49 UTC, eu-genia approved these changes

2024-11-18 08:45 UTC, CarstenHoffmannMarburg requested changes

2024-11-18 08:45 UTC, CarstenHoffmannMarburg commented on Frankfurt/FSUor16.xml
> +                <title>Prayers, <foreign xml:lang="gez">Maṣḥafa falasfā ṭabibān</foreign>, <foreign xml:lang="gez">Hāymānotu la-qǝddus ʿābiyy māri Yāʿqob ʾƎlbarādʿi</foreign></title>
You preferred fal**ā**sfā (with 'long' **ā** in the middle) in the LIT records in https://github.com/BetaMasaheft/Works/pull/1322/files and in other records in this branch.

2024-11-18 08:45 UTC, CarstenHoffmannMarburg commented on ParisBNF/abb/BNFabb122.xml
> +           <title>Book of Sirach, Canon of the Doctors of the Church for those who Abjure, <foreign xml:lang="gez">Maṣḥafa falāsfā ṭabibān</foreign>, and other texts</title>
I think 'abjure' should not be capitalised. Semantically, it is perhaps more convenient to use the more frequent 'renounce'.

2024-11-18 15:10 UTC, nafisa-valieva approved these changes
Thank you, Massimo! very helpful!

2024-11-19 07:44 UTC, merged