RDW009
BetaMasaheft/Manuscripts pull request #2740
Opened 2024-12-11 13:47 UTC by thea-m

old branch

2024-12-13 09:17 UTC, CarstenHoffmannMarburg requested changes

2024-12-13 09:17 UTC, CarstenHoffmannMarburg commented on Hamburg/HLC/RDW009.xml
> +               <lb n="1"/><hi rend="rubric">በስመ አብ ወልድ
word dividers missing throughout

2024-12-16 11:23 UTC, MagdaKrzyz approved these changes

2024-12-16 11:24 UTC, MagdaKrzyz approved these changes

2024-12-16 13:10 UTC, merged