Nv mss containing henok
BetaMasaheft/Manuscripts pull request #2745
Opened 2024-12-16 11:29 UTC by nafisa-valieva

Hello! I have introduced tiny-tiny changes to the manuscripts containing Henok to make them appear in the ´red box'. I have limited my intervention to LIT1340EnochE.

2024-12-16 13:09 UTC, thea-m requested changes
Thank you, that is very useful! Could you please add a change element describing your addition to each of the files, so that your work will be acknowledged?

2024-12-16 13:11 UTC, nafisa-valieva commented
> Thank you, that is very useful! Could you please add a change element describing your addition to each of the files, so that your work will be acknowledged?

should I?

2024-12-16 13:13 UTC, thea-m commented
I think so, what would would speak against it? It is the official workflow, and the only way to make your work become easily visible on the website. You can also acknowledge potential other sources in the change element, e.g. "added ID LIT1340EnochE based on article XX"

2024-12-17 06:21 UTC, karljonaskarlsson approved these changes

2024-12-17 06:21 UTC, karljonaskarlsson commented on EMML/6001-7000/EMML6686.xml
> +                     <origDate notBefore="1600" notAfter="1700">17th century, </origDate>
Maybe even just "17th century"?

2024-12-17 06:21 UTC, karljonaskarlsson commented on EMML/7001-8000/EMML7103.xml
> +                     <note>Date given as Year of the World 7152 on f. 27a: ተፈጸመ፡ ዝንቱ፡ መጸሐፈ፡ ሄኖክ፡
Maybe "መ<sic resp="NV">ጸ</sic>ሐፈ፡"? (I checked the ms)

2024-12-17 06:21 UTC, karljonaskarlsson commented on EMML/7001-8000/EMML7103.xml
> +                        በ፸፻ወ፩፻፶ወ፪ዓመት፡ እምፍጥረተ፡ ዓለም፡ በዘመነ፡ የሐንስ፨</note>
ዮሐንስ (I checked the ms)

2024-12-17 06:21 UTC, karljonaskarlsson commented on EMML/7001-8000/EMML7584.xml
> +                  <summary>ff. 1r–27v: 1 Enoch —ff. 28r–40r: Job110; ff. 41r–42v: Song of Songs; ff.
Do we know what "Job110" means?

2024-12-17 06:21 UTC, karljonaskarlsson commented on EMML/7001-8000/EMML7584.xml
> +                     Maccabees111 (incomplete) </summary>
Same, what does "Maccabees111" mean? Is it a copypasted page number?

2024-12-17 09:03 UTC, thea-m commented
@karljonaskarlsson , I think that the errors you rightly highlighted were already present in the files to which Nafisa only added one ID, and editing the whole files was not part of her work process right now. That is not to say that they may not be corrected, if anyone is in the mood, but this was not the main focus :)

2024-12-17 09:12 UTC, karljonaskarlsson commented
> @karljonaskarlsson , I think that the errors you rightly highlighted were already present in the files to which Nafisa only added one ID, and editing the whole files was not part of her work process right now. That is not to say that they may not be corrected, if anyone is in the mood, but this was not the main focus :)

Yes, no corrections are obligatory :) I just noted what struck me in the parts that had been changed.

2024-12-17 15:45 UTC, thea-m approved these changes

2024-12-17 16:33 UTC, nafisa-valieva commented
> > @karljonaskarlsson , I think that the errors you rightly highlighted were already present in the files to which Nafisa only added one ID, and editing the whole files was not part of her work process right now. That is not to say that they may not be corrected, if anyone is in the mood, but this was not the main focus :)
> 
> Yes, no corrections are obligatory :) I just noted what struck me in the parts that had been changed.
> 
> And some things, like these numbers within the text identifications, may even be difficult to correct, without figuring out what is going on… but on the other hand, this could be an occasion to correct them. If someone is in the mood :D

I will merge the changes and then the files will be available for further improvements (by someone else, not me)!

2024-12-17 16:33 UTC, merged

2024-12-18 08:24 UTC, eu-genia commented on EMIP/1-1000/EMIP00937.xml
> +                     <title ref="LIT1340EnochE">Henok</title>
I have not seen this one.

This cannot be ms_i1. 

i1 are Prophets
then you have i1.1 Hosea, i1.2 Amos etc.

or no ms_i at all

Thank you

2024-12-18 08:25 UTC, eu-genia commented on EMML/6001-7000/EMML6686.xml
> +                     <locus from="4r" to="27r"/>
as above

2024-12-18 08:25 UTC, eu-genia commented on EMML/6001-7000/EMML6686.xml
> +                     <locus from="4r" to="27r"/>
and then someone wants to have all witnesses for Jeremiah and has to redo?