2024 12 06 jk uub o etiop 45
BetaMasaheft/Manuscripts pull request #2753
Opened 2024-12-20 18:13 UTC by karljonaskarlsson

Added description of UUB O Etiop. 45 (http://www.alvin-portal.org/alvin/view.jsf?pid=alvin-record%3A489055&dswid=3967) based primarily on the catalogues and added work to Portland, Ethiopic Manuscript Imaging Project, Weiner Codex 157 based on a new identification (based on comparison with UUB O Etiop. 45).

2024-12-20 19:39 UTC, CarstenHoffmannMarburg requested changes

2024-12-20 19:39 UTC, CarstenHoffmannMarburg commented on Uppsala/UppEt45.xml
> +                                    From the top of his head, two snakes emerges, one reaching towards the left
emerge

2024-12-20 19:39 UTC, CarstenHoffmannMarburg commented on Uppsala/UppEt45.xml
> +                                <bibl><ptr target="bm:Loefgren1962Wandamulette"/><citedRange unit="page">105</citedRange></bibl>
Loefgren against Loefgren?

2024-12-20 19:39 UTC, CarstenHoffmannMarburg commented on Uppsala/UppEt45.xml
> +                            <ref type="mss" corresp="#UppEt46"/>, the original owner can be
How can an information from UppEt46 prove the ownership of UppEt45?

2024-12-20 19:39 UTC, CarstenHoffmannMarburg commented on Uppsala/UppEt45.xml
> +                            According to <ref target="e4"/>, manuscript reached its current repository in <date when="1968"/>.
the manuscript

2025-01-06 11:07 UTC, thea-m requested changes
Thank you, very nice!

2025-01-06 11:07 UTC, thea-m commented on Uppsala/UppEt45.xml
> +                                    <note>Composed of one strip.</note>
could you encode the number of strips, see guidelines:   `<note>Consists of <measure unit="strips">3</measure> strips.</note>`

2025-01-06 11:07 UTC, thea-m commented on Uppsala/UppEt45.xml
> +                                <desc>Able hand of the 19th century (<foreign xml:lang="de">von einer habilen Hand des 19. Jahrhunderts</foreign>,
I find "able" unusual, and leading to the association of ableism from my part :) Maybe "skilled" might be used?

2025-01-06 11:07 UTC, thea-m commented on Uppsala/UppEt45.xml
> +                                    The picture is placed in a field of 42 cm height, which it almost fills.
really 42 cm, not mm?
Does the catalogue provide any information on where in the scroll the picture is located?
The dimension can also be encoded, see guidelines:
  ```
<decoNote xml:id="d2" type="drawing" corresp="#pic2">
                            <desc>Monochrome drawing of a magic square, possibly a <ref type="authFile" corresp="AT1140SealSol"></ref>, but without face.</desc>
                            <dimensions unit="mm">
                                <height>75</height>
                                <width>46</width>
                            </dimensions>
                        </decoNote>
```

2025-01-06 11:07 UTC, thea-m commented on Uppsala/UppEt45.xml
> +                            Evangeliska fosterlandsstiftelsen and brought to Sweden. During a period,
Maybe "for a while"? "during a certain/unknown period"?

2025-01-06 11:07 UTC, thea-m commented on Uppsala/UppEt45.xml
> +                            According to <ref target="e4"/>, manuscript reached its current repository in <date when="1968"/>.
`#e4`

2025-01-07 07:57 UTC, karljonaskarlsson commented on Uppsala/UppEt45.xml
> +                                <bibl><ptr target="bm:Loefgren1962Wandamulette"/><citedRange unit="page">105</citedRange></bibl>
Yes! :) I will clarify

2025-01-07 08:02 UTC, karljonaskarlsson commented on Uppsala/UppEt45.xml
> +                            <ref type="mss" corresp="#UppEt46"/>, the original owner can be
As I write, Löfgren suggests that they were all produced in the same context for the same original owner and later all passed into the possession of the same secondary owner.

2025-01-07 08:09 UTC, karljonaskarlsson commented on Uppsala/UppEt45.xml
> +                                    The picture is placed in a field of 42 cm height, which it almost fills.
Yes, cm! :) 

I technically don't have the measurements of the image, only of the field where it appears…

<img width="170" alt="Skärmavbild 2025-01-07 kl  09 08 00" src="https://github.com/user-attachments/assets/3e964615-1f0c-4117-a680-6122718f076e" />

2025-01-07 08:11 UTC, karljonaskarlsson commented on Uppsala/UppEt45.xml
> +                                <desc>Able hand of the 19th century (<foreign xml:lang="de">von einer habilen Hand des 19. Jahrhunderts</foreign>,
For me, "able" sounds good, but many minds working together produce greater results :)

2025-01-07 09:18 UTC, thea-m approved these changes

2025-01-07 09:27 UTC, CarstenHoffmannMarburg commented on Uppsala/UppEt45.xml
> +                                <desc>Able hand of the 19th century (<foreign xml:lang="de">von einer habilen Hand des 19. Jahrhunderts</foreign>,
It maybe, that "able" sound obsolet or politically incorrect nowadays, but this is also the case for "von einer habilen Hand". I would propose to mark "able" with quotation marks "able" or 'able'.

2025-01-07 09:33 UTC, CarstenHoffmannMarburg commented on Uppsala/UppEt45.xml
> +                            <ref type="mss" corresp="#UppEt46"/>, the original owner can be
I would prefer "As for ...", but it is okay for me like this.

2025-01-07 09:34 UTC, CarstenHoffmannMarburg approved these changes

2025-01-07 10:00 UTC, merged