Create BLadd19339.xml
BetaMasaheft/Manuscripts pull request #731
Opened 2020-08-18 10:50 UTC by DariaElagina

2020-08-18 11:32 UTC, DenisNosnitsin1970 commented on LondonBritishLibrary/add/BLadd19339.xml
> +                            ዘእስክንድርያ።</persName> ኀበ፡ ኵሎሙ፡ አብያተ፡ ክርስቲያናት፡ ዘኢትዮጵያ፡ በእዴሁ፡ ላጳጳስነ፡ መቃርዮስ፡
ለጳጳስነ

2020-08-18 12:12 UTC, DenisNosnitsin1970 commented on LondonBritishLibrary/add/BLadd19339.xml
> +                                    <desc type="Unclear">Comment on the manuscript contect in
content

2020-08-19 07:26 UTC, thea-m requested changes
Interesting!

2020-08-19 07:26 UTC, thea-m commented on LondonBritishLibrary/add/BLadd19339.xml
> +                        ርትዕት፡ ሃይማኖተ፡ እስክንድያ፤ መንበረ፡ ስብከቱ፡ ለማርቆስ፡ ሐዋርያ።<gap reason="ellipsis"></gap>
እስክንድርያ?

2020-08-19 07:26 UTC, thea-m commented on LondonBritishLibrary/add/BLadd19339.xml
> +                          from the Library of the Earl of <placeName ref="wd:Q1081960">Mountnorris</placeName>.</provenance>
you could also mark him up as a person (I think PRS1950Annesley)

2020-08-19 07:26 UTC, thea-m commented on LondonBritishLibrary/add/BLadd19339.xml
> +                            <origDate notBefore="1808" notAfter="1867" evidence="lettering"/>
the ante quem could probably be the date of Salt's return from Ethiopia? (That's how I would understand the English note, or do you think the letter was copied from the one given to Salt?)

2020-08-31 07:14 UTC, thea-m approved these changes

2020-08-31 07:15 UTC, merged