Update BLorient795.xml
BetaMasaheft/Manuscripts pull request #793
Opened 2020-09-29 13:51 UTC by DariaElagina

2020-09-29 14:00 UTC, DenisNosnitsin1970 approved these changes

2020-09-29 14:02 UTC, thea-m reviewed
I have a few remarks, but can come to it only on Thursday. Can the work not be identified?

2020-09-29 14:02 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient795.xml
> +                           <desc>Name of the owner <persName ref="PRS13173WaldaK" role="owner"></persName>
The names of...

2020-09-29 14:06 UTC, DariaElagina commented
Whenever you have time. No the work can't be identified, there is no incipit or whatever.

2020-09-30 15:04 UTC, thea-m requested changes
Thank you for your patience!

2020-09-30 15:04 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient795.xml
> +                     <title type="complete" xml:lang="en">Of the Holy Spirit.</title>
Wright's chapters seem to correspond to the ones given in the work record. So you could maybe add the reference to all chapters in the title? And conversely, I would add the chapter titles in the work records, but that might be personal preference.

2020-09-30 15:04 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient795.xml
> +                     <note>The rubrics are partly lacking.</note>
See above - if we assume that it's about rubrication, I would say that the extra is actually enough

2020-10-19 08:04 UTC, thea-m approved these changes

2020-10-19 08:04 UTC, merged