Multiple mss
BetaMasaheft/Manuscripts pull request #836
Opened 2020-10-27 17:08 UTC by DenisNosnitsin1970

Corrections,  LIT5069Prayer and LIT6205Saalnaka

2020-10-28 07:54 UTC, thea-m requested changes

2020-10-28 07:54 UTC, thea-m commented on DayrSuryan/DSEthiop9.xml
> +                         <hi rend="rubric">በስመ፡ አብ ወወልድ፡ <sic resp="DR">ወመንፈንስ፡</sic> ቅዱስ፡</hi>
I think that this change has been carried out to change the visualisation. @PietroLiuzzo the fact that `<sic>` is not yet rendered as (!) after the word (not the letter) does not mean that it is possible, right?

2020-11-01 17:31 UTC, DenisNosnitsin1970 commented
Can this be merged?

2020-11-02 09:23 UTC, thea-m commented on DayrSuryan/DSEthiop9.xml
> +                         <hi rend="rubric">በስመ፡ አብ ወወልድ፡ <sic resp="DR">ወመንፈንስ፡</sic> ቅዱስ፡</hi>
@PietroLiuzzo could you confirm (or correct me)?

2020-11-02 09:24 UTC, thea-m commented
I still think that changing the exact markup of sic is not necessary, let's wait for @PietroLiuzzo 's answer

2020-11-24 09:56 UTC, DenisNosnitsin1970 commented
Dorothea, let us merge it?

2020-11-24 10:34 UTC, thea-m approved these changes

2020-11-24 10:37 UTC, merged