B lorient802
BetaMasaheft/Manuscripts pull request #844
Opened 2020-11-03 11:01 UTC by MarcinKrawczuk

2020-11-10 10:17 UTC, DariaElagina requested changes

2020-11-10 10:17 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient802.xml
>                                      <dimensions type="outer" unit="mm">
I think the catalogue provide inches, it should be changed to inches

2020-11-10 10:17 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient802.xml
> +                           <desc type="MixedNote">Lists of lands, in Amharic.</desc>
please, add an empty q with lang

2020-11-10 10:17 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient802.xml
>                              <origDate/>
the date can be provided based on the colophon

2020-11-10 10:17 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient802.xml
>          <fileDesc>
add also your name as the editor

2020-11-10 10:17 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient802.xml
> +
`<term key="ChristianLiterature"/>
<term key="CanonLaw"/>
<term key="Translation"/>
<term key="Paks2"/>`

2020-11-16 13:45 UTC, thea-m approved these changes
Thank you!

2020-11-16 13:50 UTC, merged