Um039
BetaMasaheft/Manuscripts pull request #872
Opened 2020-11-19 14:30 UTC by eu-genia

Work IDs are in progress of creation, but I have used derived IDs for now

2020-11-20 07:46 UTC, thea-m requested changes
minor questions, thank you

2020-11-20 09:27 UTC, eu-genia commented on ES/ESum039.xml
> +               <msContents><summary/>
This is the msContents element with the summary to have the entire summary for the whole MS on top, I always do it (and hope everyone does) for composite manuscripts, where the actual contents is described further for each part separately

2020-11-20 09:28 UTC, eu-genia commented on ES/ESum039.xml
> +                                 <item xml:id="q1" n="I">
@PietroLiuzzo is it a problem to use the Roman numbers? I tried to keep as much as possible from the "source" description

2020-11-23 13:56 UTC, eu-genia commented on ES/ESum039.xml
> +                                 <item xml:id="q1" n="I">
I have updated the numbers to Arabic

2020-11-23 13:58 UTC, eu-genia commented on ES/ESum039.xml
> +               <msContents><summary/>
(after the physical description of the entire MS there is no msContents, there are separate msContents for each msPart)

2020-11-23 13:58 UTC, thea-m approved these changes

2020-11-23 13:59 UTC, merged