B lorient549
BetaMasaheft/Manuscripts pull request #899
Opened 2020-12-02 19:46 UTC by MarcinKrawczuk

This one is ready except I wasn't able to identify ms_i13 without the text.

The discussion of the forum (https://github.com/BetaMasaheft/Documentation/issues/1578) wasn't very helpful.

2020-12-07 16:27 UTC, DariaElagina requested changes

2020-12-07 16:27 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<note>The writing on <locus target="#61v">f. 61v</locus> and <locus target="#62r">62r</locus> has been erased.</note>
One could now pose our favourite question if the text is still complete :) what do you think, @thea-m , @DenisNosnitsin1970 ?

2020-12-07 16:27 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +
the q element should follow the desc, and not be inside of it

2020-12-07 16:27 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<desc type="OwnershipNote">Names of certain owners.</desc>
#3r

2020-12-07 16:27 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +</item>
the names could be encoded, as they are in the following e2

2020-12-07 16:27 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<desc type="OwnershipNote">Names of certain owners.</desc>
#50v

2020-12-07 16:27 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<desc>On <locus target="3v">f. 3v</locus> the name of king ʾIyāsu, probably <persName ref="PRS5618IyasuII">ʾIyāsu III</persName>,
rather target?

2020-12-07 16:27 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<desc type="MixedNote"><q xml:lang="gez"/>A list of the sacred books which may be read in the Church.</desc>
the q element should follow the desc element

2020-12-07 16:27 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<desc type="MixedNote"><q xml:lang="gez"/>A list of the sacred books which may be read in the Church.</desc>
I wonder if it should be promoted to additions

2020-12-07 16:27 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +
The q element should follow, I would encode it as an addition as well

2020-12-07 16:30 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<note>The writing on <locus target="#61v">f. 61v</locus> and <locus target="#62r">62r</locus> has been erased.</note>
I think this could be the case for Syntaxe du Codex, would you agree?

2020-12-08 16:31 UTC, DariaElagina requested changes

2020-12-08 16:31 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<q xml:lang="amh"/>
am for Amharic

2021-01-04 12:58 UTC, DariaElagina requested changes

2021-01-04 12:58 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<note>The writing on <locus target="#61v">f. 61v</locus> and <locus target="#62r">62r</locus> has been erased.</note>
I guess the text is anyway incopmple, as if the folia would have been torn out

2021-01-04 12:58 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<desc type="OwnershipNote">Names of certain owners.</desc>
The ' in >' should be deleted

2021-01-04 12:58 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<desc type="OwnershipNote">Names of certain owners.</desc>
Here again a ' after locus. No idea, if it could cause problems

2021-01-04 12:58 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<desc>On <locus target="3v">f. 3v</locus> the name of king ʾIyāsu, probably <persName ref="PRS5618IyasuII">ʾIyāsu III</persName>,
#3v

2021-01-04 12:58 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient549.xml
> +<desc>On <locus target="3v">f. 3v</locus> the name of king ʾIyāsu, probably <persName ref="PRS5618IyasuII">ʾIyāsu III</persName>,
You can encode the ceratainty as well. Search for certainty in the GL

2021-02-02 18:56 UTC, DariaElagina approved these changes

2021-02-02 18:57 UTC, merged

2021-02-11 09:13 UTC, eu-genia commented
I only now saw this PR as i was retagged in the issue 1578 - as I wrote there on 24 November the ms_i13 is LIT4020RegulaeHierarchia  https://github.com/BetaMasaheft/Documentation/issues/1578#issuecomment-732885205
please update the record and close the issue, thank you