Bl orient 812
BetaMasaheft/Manuscripts pull request #924
Opened 2020-12-16 13:36 UTC by DariaElagina

2020-12-16 17:47 UTC, DenisNosnitsin1970 approved these changes

2020-12-17 08:56 UTC, thea-m requested changes
Thank you!

2020-12-17 08:56 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient812.xml
> +                                A rude table of the signs of Zodiac.
@smaugustine , can you help us? I always wonder if Wright's "rude" (which probably means what is described as "crude"  for instance in Ethio-SPaRe descriptions) would sound strange to modern English speakers and should be substituted by another word in these descriptions.

2020-12-17 08:56 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient812.xml
> +                              <!-- the numbers are not conform to the traditional system, Mark V is
I think that his could be changed into a note: if you noticed this, others also might find it interesting.

2020-12-17 08:56 UTC, thea-m commented on LondonBritishLibrary/orient/BLorient812.xml
> +                              <title type="complete" xml:lang="en">The list of ʾabunās of Ethiopia</title>
ʾabuna, not ʿabunā?

2021-01-12 15:37 UTC, thea-m approved these changes

2021-01-12 15:37 UTC, merged