Bl or573 mk
BetaMasaheft/Manuscripts pull request #929
Opened 2020-12-17 17:30 UTC by MarcinKrawczuk

Please not then in some cases I have taken data from the mss. directly and not from the catalogue.

2020-12-17 17:35 UTC, smaugustine commented
ms_i1.52 is missing a ref, it's Chaîne no. 237 (`LIT2956RepCh237`).

I had this MS in my own database of Malkǝʾa Gubāʾe MSS and contents, along (partially or fully) with the others (575, 578, etc.), sorry for not mentioning it.

2021-01-04 16:55 UTC, DariaElagina requested changes

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<textLang mainLang="gez"/>
I guess it is LIT2741RepCh25

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<title xml:lang="gez" type="complete" ref="LIT2842RepCh125"><foreign xml:lang="gez">መልክአ፡ መስቀል፡</foreign></title>
just put xml:lang into the title element, and you do not need foreign

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<textLang mainLang="gez"/>
Please, add xml:lang to the incipit here and below

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +</msItem>
Same here and below

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<title xml:lang="gez" type="complete" ref="LIT2999RepCh279">To S. John the Evangelist</title>
St

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<incipit>ሰላም፡ ለዝክረ፡ ስምክሙ፡ ዘአልባስጥሮስ፡ አፈው።</incipit>
St

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<incipit>ሰላም፡ ለዝክረ፡ ስምከ፡ ዘሰሌዳ፡ ሞገስ፡ መጽሐፉ።</incipit>
St

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<incipit>በስመ፡ ሥሉስ፡ ቅዱስ፡ እግዚአብሔር፡ አሐዱ።</incipit>
St

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<incipit>ሰላም፡ ለፅንሠትከ፡ እንበለ፡ ያእምሩ፡ አዝማዲከ።</incipit>
St here and below

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<incipit>ሰላም፡ ለሕማምከ፡ ቤተ፡ አይሁድ፡ ዘአንደደ፡ ወረሰዮሙ፡ ሐመደ።</incipit>
here the xml:lang="gez" in the title is wrong, it is English. The same applies for many cases below

2021-01-04 16:55 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +legible e. g. on <locus target="#231v">f. 231v</locus>.</desc>
I guess the information that the name of the owner has been erased should be added to extras. BTW, you do need to write out the names, if they are marked up they will be retrieved from the corresponding file

2021-01-20 09:16 UTC, DariaElagina requested changes

2021-01-20 09:16 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +</msItem>
xml: lang in incipit

2021-01-20 09:16 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<incipit xml:lang="gez">ሰላም፡ ለፅንሠትከ፡ ወለልደትከ፡ እማኅፀን።</incipit>
xml:lang in title? en or gez?

2021-01-20 09:16 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<title xml:lang="en" type="complete" ref="LIT2916RepCh197">To S. Matthias(<foreign xml:lang="gez">ማትያስ፡</foreign>) for the 8th of Magābit</title>
St

2021-01-20 09:16 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +legible e. g. on <locus target="#231v">f. 231v</locus>.</desc>
the type is not needed here, it  is rather a phenomena (the name was erased throughout the mansucript) than a specific text, I guess

2021-01-28 16:38 UTC, DariaElagina commented on LondonBritishLibrary/orient/BLorient573.xml
> +<textLang mainLang="gez"/>
Sorry, I can not see the changes here, or is my assumption wrong?

2021-02-08 09:18 UTC, DariaElagina approved these changes

2021-02-08 09:19 UTC, merged