Update BLorient810.xml
BetaMasaheft/Manuscripts pull request #933
Opened 2020-12-22 12:32 UTC by DariaElagina

2020-12-22 13:09 UTC, eu-genia requested changes

2020-12-22 13:09 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient810.xml
> +                          <msItem xml:id="ms_i1.6">
since we have no to="" loci here, I would keep the notes for the missing chapters (47, 51, etc.) to make the composition more evident

2020-12-22 13:09 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient810.xml
> +                            <title type="complete" ref="LIT1011Abusak#Chapter52"></title>
I guess when Wright says "Chapter 52" etc. he means that there is the corresponding label in the text, so am wondering if it should be put inside of the `<title>` tag or as a `<rubric>`

2020-12-22 13:09 UTC, eu-genia commented on LondonBritishLibrary/orient/BLorient810.xml
> +                              book <foreign xml:lang="gez">አቡሻክር፡</foreign> belonged to
I would mark the title up as the title, if we later want to filter for books where the title is noted - or at least keep the wording of Wright here (a note containing the name of the book)

2020-12-22 18:24 UTC, DenisNosnitsin1970 requested changes

2020-12-22 18:24 UTC, DenisNosnitsin1970 commented on LondonBritishLibrary/orient/BLorient810.xml
> +                            <textLang mainLang="gez"></textLang>
From the description it is now not clear where are chapters 2-48, it looks like a mistake. Can their presence be indicated as ms-items without just loci?

2021-01-06 23:08 UTC, eu-genia approved these changes

2021-01-12 15:18 UTC, DariaElagina commented
@DenisNosnitsin1970  I guess I have solved the problem

2021-01-28 16:31 UTC, DariaElagina commented
Can this be merged, @DenisNosnitsin1970 ?

2021-01-28 16:34 UTC, merged