New ham gg
BetaMasaheft/Manuscripts pull request #957
Opened 2021-01-26 09:18 UTC by PietroLiuzzo

please note that this PR includes a split file, which is still experimental. I will use it to test functionality to support this.

2021-01-26 12:03 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/CCRsourceDesc.xml
> +            -->
yes

2021-01-26 12:10 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/CCRsourceDesc.xml
> +            <msPart xml:id="p2CCR">
Qirqos (!)

2021-01-26 12:31 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +          <seg type="rubrication">Some words rubricated.</seg>
Personal names, numerals' stokes and punctuation marks

2021-01-26 12:51 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +          <!--          please Nafisa could you tell me what these are and if consistent with the rest of the text on this page?-->
It is a separate note by a certain Gabra Hǝywat, it has nothing to do with what follows

2021-01-26 13:05 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +            <pb/><cb/>ሎት፡ በስኢል፡ ወበስጊድ፡ ለዓለመ፡ ዓለም። <lb/><space/>
I thik CCR 22 can be treated as one document ending up with a prayer, which is its part

2021-01-26 13:15 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +            document.</note>
CCR 19 does not need to be splitted, I was too passionate

2021-01-26 13:16 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +<!--         this was listed twice, incipit is different, explicit also, same alignment to Bausi's list...-->
Yes, because Bausi does treat them as one

2021-01-26 13:24 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +          <incipit>አውሎግሶን፡ ጽደዙ፡ ዘአዘዙ፡ ንጉሥነ፡ ርቱዐ፡ ሃይማኖት፡ ሰይፈ፡ አርዓድ፡ ወስመ፡ መንግሥቱ፡ ቈስጠንጢኖስ፡ </incipit>
ጽደቁ፡ is the second Ethiopic word

2021-01-26 14:02 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +<!--              what is on line 1?-->
locus 20r1-20v12,
the incipit does not include the invocation as typical, but may be this needs to be changed

2021-01-26 14:03 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +<!--              better locus needed, copied from previous msItem-->
no need for splitting

2021-01-26 14:05 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +              <locus from="20v13" to="22r8"/>
22v8

2021-01-26 14:06 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +              <locus from="22v5" to="22v9"/>
no need for splitting

2021-01-26 14:14 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +                  <!--                  what about ወአሜን at the end of line 18? it is not included in the explicit of p7_i11=LIT6325CCR18=CCR18-->
I do not understand

2021-01-26 14:15 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +              <explicit>ወእመቦ፡ ዘደምሰሳ፡ ወዘቀደዳ፡ በጽልሑት፡ ከማሁ፡ ለይኩን፡ ውጉዘ፡ ለዓለመ፡ ዓለም፡ አሜን። </explicit>
+ ወአሜን።

2021-01-26 14:16 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +                  <!--                  what about ወአሜን at the end of line 18? it is not included in the explicit of p7_i11=LIT6325CCR18=CCR18-->
Yes, right point

2021-01-26 14:25 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +              <!--              I think this should be LIT6305CCR7, and there should be no second work record
it is a bit question whether it is one text or two. But I am ready to accept them as one. eshy. you won :-)

2021-01-26 14:34 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +<!--              not sure about this placement... the transcription is all messed up, the image hard to read.
yes from line 16 to the end of the page, I count to 24, but not sure either.

2021-01-26 14:37 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +                  <del rend="erasure"/>
Nafisa's bad idea

2021-01-26 14:40 UTC, nafisa-valieva commented on Ham/DabraLibanosHamGG1/msDesc.xml
> +<!--                  not sure about the placement of this, expecially given the explicit of the previous item and the del markup which is mysteriuous-->
it starts on line 22 to 28

2021-01-26 14:49 UTC, nafisa-valieva commented
Ciao Pietro,
Great work! I have made some comments while reading the text, I hope it is fine. I see some mistakes in my own transcription, but I think I prefer to check everything at the very end of our work, may be seeing it online and having new layout and new impressions in general. I have not checked the text transcribed with Transcribus, do you want me to do it?

Yours,
Nafisa

2021-01-26 14:54 UTC, nafisa-valieva requested changes
Dear Pietro,
great work! here my comments on our file (I went through others as well, but I understand very little)
In general I see some errors in my transcription, I would like to revise them when we are close to the end. I also want to check hands identifications once again.
Quiros is Qirqos,
CCR 19 and CCR 20, CCR 22 in both sets should be reunited, it was not a good idea, and I also give up upon my ideas on CCR 6 a and b and 7a and b :-) 
concerning locus and incipits: as a general practice I have skipped the invocation formula in the incipits, if you think it is confusing, I can add it, it is easy. But as a result, it affected your understanding of locus sometimes, so I noted it.
Yours, Nafisa

2021-01-26 15:01 UTC, PietroLiuzzo reviewed
Dear Nafisa, for the transcription checking, let us see if it is worth, for now I would think it is not a priority.

2021-01-26 15:02 UTC, PietroLiuzzo commented
ok, I will make the necessary changes. thanks!

2021-02-05 10:50 UTC, PietroLiuzzo commented
@nafisa-valieva I think I have done what needed doing for CCR6, 7, 19, 20 and 22. I am not sure about the loci. I think, technically speaking we need to be inclusive with those, they need to say where a text starts, inclusive of any formulaic element. it would be very interesting to mark in the transcription or in the work record, using the EMA methodology, the various parts of the documents.

2021-02-05 11:08 UTC, PietroLiuzzo commented
@nafisa-valieva , I think this is ready to go. if you are ok with it I will proceed to merge https://github.com/BetaMasaheft/Works/pull/460 and then this one, I need to do this myself because I updated the syncing script and i need to observe and test using this PR.

2021-02-05 12:53 UTC, merged

2021-02-05 14:00 UTC, PietroLiuzzo commented
Dear @nafisa-valieva the test has gone well for the step being tested, but please, do not worry too much about the current, broken, view of the manuscript online. because it has new encoding, it has been submitted in a new way and as part of a major rearchitecturing of the backend, it is behaving better than expected. with the new release this will go fine, for the time being I will simply do a work around.

2021-02-05 14:07 UTC, nafisa-valieva commented
Ok! Thank you for this word of warning :-) For now I cannot see anything online, it gives only error.

2021-02-05 15:12 UTC, PietroLiuzzo commented
well, there are a couple of errors which I can also see but "only error" is perhaps a bit too much? what are you experiencing?

2021-02-05 15:19 UTC, nafisa-valieva commented
iiii! now I see it too!